"""`.authored.yaml` — the only file in this pipeline a human writes (#455).

Three files per scene, the shape `transcript_corrections.yaml` already
established for the tape one layer down:

    session_doc_scene_NN_<slug>.md             generated by sd_narrate
    session_doc_scene_NN_<slug>.authored.yaml  THIS — hand-authored
    session_doc_scene_NN_<slug>.composed.md    generated by composing the two

**The record is the source of truth and the composed document is output.** That
rule exists because the alternative was measured: before it, the tape's cleaned
variant carried 74 unrecorded substitutions made by a chat-driven pass, three of
which wrote a surname nobody said into the ground truth. Nothing enumerated the
edits, so nothing could review them.

**Only what the human contributed is stored.** A block nobody touched has no
entry — `unruled` is an absence, not a value. That keeps a part-way record small
and makes "how much is ruled" a count of entries rather than a scan for a
sentinel.

**`mine` and `authored` are stored distinctly**, never inferred from whether
`text` is present. "I ruled this mine and have not written it" is the normal end
state of a review done on a phone; "I ruled this mine and wrote an empty string"
is something else. Inferring would merge exactly the work a mobile session
produces.
"""

from __future__ import annotations

from datetime import date
from pathlib import Path

import yaml
from pydantic import BaseModel, ConfigDict, ValidationError, field_validator, model_validator

#: Conventional suffix, beside the narration it governs.
RECORD_SUFFIX = ".authored.yaml"

#: Bumped when the record's shape changes incompatibly. An unknown version is
#: refused rather than ignored, the same call `transcript_corrections` makes.
RECORD_VERSION = 1

#: What the human decided about one block.
#:
#: `unruled` is deliberately absent: it is the state of a block with no entry.
DISPOSITIONS = ("mine", "authored", "cut", "edited")

#: Feedback on the *marking*, orthogonal to the disposition and never reaching
#: the composed document. This is how a GM says the contract gapped the wrong
#: thing — the signal #454's re-confirmation showed is worth keeping, since all
#: 31 accepted gaps came back "right gap, mine to write".
CRITIQUES = ("wrong-scope", "model-should-have-written")


class AuthoredError(Exception):
    """The record could not be loaded, or does not fit the narration."""


class _Strict(BaseModel):
    model_config = ConfigDict(extra="forbid")


class AuthoredBlock(_Strict):
    """One block the human touched."""

    id: str
    disposition: str
    text: str | None = None
    #: The text started as the model's own summary of the gap — the marker's
    #: sentence — which the GM accepted rather than writing their own.
    #:
    #: Accepting it is a real ruling, not a shortcut past the checkpoint: a human
    #: read the sentence and said it was right, which is the whole gate. But the
    #: chapter then carries a sentence the model wrote, and "did a person write
    #: this line?" is a question somebody asks later. `authored` alone would
    #: answer it wrongly, and this repo does not let provenance go unrecorded.
    from_summary: bool = False
    critique: str | None = None
    note: str | None = None
    anchor: str = ""
    recorded: date | None = None
    recorded_by: str = "GM"

    @field_validator("id")
    @classmethod
    def _id_non_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("id must be a block id such as 'gap-3' or 'prose-7'")
        return v

    @field_validator("disposition")
    @classmethod
    def _known_disposition(cls, v: str) -> str:
        if v not in DISPOSITIONS:
            raise ValueError(
                f"disposition must be one of {', '.join(DISPOSITIONS)}, not {v!r}. "
                f"A block nobody ruled on has no entry at all."
            )
        return v

    @field_validator("critique")
    @classmethod
    def _known_critique(cls, v: str | None) -> str | None:
        if v is not None and v not in CRITIQUES:
            raise ValueError(f"critique must be one of {', '.join(CRITIQUES)}, not {v!r}")
        return v

    @model_validator(mode="after")
    def _text_matches_disposition(self) -> "AuthoredBlock":
        if self.disposition in ("authored", "edited") and self.text is None:
            raise ValueError(
                f"block {self.id!r} is {self.disposition!r} but carries no text. "
                f"Use 'mine' for a gap you have ruled yours and not yet written."
            )
        if self.disposition == "cut" and self.text:
            raise ValueError(
                f"block {self.id!r} is cut but also carries text; which one wins "
                f"would be a guess"
            )
        return self


class AuthoredRecord(_Strict):
    """One scene's rulings and prose."""

    version: int = RECORD_VERSION
    narration: str
    generated_sha256: str
    blocks: list[AuthoredBlock] = []

    @field_validator("version")
    @classmethod
    def _known_version(cls, v: int) -> int:
        if v != RECORD_VERSION:
            raise ValueError(
                f"unknown record version {v!r}; this build understands "
                f"version {RECORD_VERSION}"
            )
        return v

    @model_validator(mode="after")
    def _one_entry_per_block(self) -> "AuthoredRecord":
        # Two entries for one block cannot both hold: which wins would depend on
        # file order. Exactly the reason two corrections on one cue are refused.
        seen: set[str] = set()
        for b in self.blocks:
            if b.id in seen:
                raise ValueError(
                    f"block {b.id!r} has more than one entry — merge them into "
                    f"one whose disposition and text are final"
                )
            seen.add(b.id)
        return self

    def by_id(self) -> dict[str, AuthoredBlock]:
        return {b.id: b for b in self.blocks}

    @property
    def has_authored_content(self) -> bool:
        """Is there work here a re-narrate would destroy?

        A record of pure critique, or of rulings with nothing written, is not
        nothing — but it is cheap to redo. Prose is not, and it is the only
        thing in this pipeline a human wrote from scratch.
        """
        return any(b.text for b in self.blocks)


def record_path(narration: Path) -> Path:
    return narration.with_name(narration.stem + RECORD_SUFFIX)


def load_record(path: Path) -> AuthoredRecord:
    try:
        raw = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    except OSError as exc:
        raise AuthoredError(f"cannot read {path}: {exc}") from exc
    except yaml.YAMLError as exc:
        raise AuthoredError(f"{path} is not valid YAML: {exc}") from exc
    if not isinstance(raw, dict):
        raise AuthoredError(f"{path} should hold a mapping, not {type(raw).__name__}")
    try:
        return AuthoredRecord.model_validate(raw)
    except ValidationError as exc:
        raise AuthoredError(f"{path} is not a valid authored record:\n{exc}") from exc


def load_record_for(narration: Path) -> AuthoredRecord | None:
    """The record beside a narration, or ``None`` when there is not one."""
    path = record_path(narration)
    return load_record(path) if path.is_file() else None
