#!/usr/bin/env python3
"""Create a new CampaignGenerator workspace directory.

Sets up the docs/, logs/ structure and writes a config.yaml with absolute
paths so the workspace works from any working directory.

If you already have files, point to them with --world-state, --mechanics,
--planning. The config will reference them directly (no copying).
If omitted, placeholder files are created inside the workspace.

Usage:
  python new_workspace.py ~/campaigns/icespire
  python new_workspace.py ~/campaigns/icespire --name "Icespire Peak"
  python new_workspace.py ~/campaigns/icespire \\
      --world-state ~/Phandalin/neverwinter_lore.md \\
      --mechanics   ~/Phandalin/arc_scores.md \\
      --planning    ~/Phandalin/enemy_dossiers.md
"""

import argparse
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent

CONFIG_TEMPLATE = """\
# CampaignGenerator workspace config
# Generated by new_workspace.py — edit paths here if you move files.

system_prompt: {system_prompt}

log_dir: {log_dir}

# Agent prompts for --mode pipeline (kept in the code directory)
agents:
  lore_oracle: {lore_oracle}
  encounter_architect: {encounter_architect}
  voice_keeper: {voice_keeper}

documents:
  - label: world_state
    path: {world_state}
  - label: mechanics
    path: {mechanics}
  - label: planning
    path: {planning}
  - label: party
    path: {party}
"""

WORLD_STATE_TEMPLATE = """\
# World State — {name}

_Paste or write your living canon document here._
_This is the source of truth for all session prep._
"""

MECHANICS_TEMPLATE = """\
# Mechanics — {name}

_Arc score systems, house rules, and mechanical notes go here._
"""

PLANNING_TEMPLATE = """\
# Planning — {name}

_Enemy dossiers, NPC notes, and forward-planning documents go here._
"""

PARTY_TEMPLATE = """\
# Party — {name}

_Current party roster. Keep this up to date after each session._

## Characters

| Name | Class / Level | Player | Arc Score Track |
|---|---|---|---|
| | | | |

## Arc Scores

_Define each arc score track, its current value, and trigger conditions._

## Party State

_Current location, active quests, key items held, and outstanding obligations._
"""


def resolve_existing(flag: str, value: str) -> Path:
    p = Path(value).expanduser().resolve()
    if not p.exists():
        print(f"Error: {flag} file not found: {p}", file=sys.stderr)
        sys.exit(1)
    return p


def placeholder(docs_dir: Path, filename: str, content: str) -> Path:
    p = docs_dir / filename
    p.write_text(content, encoding="utf-8")
    return p


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a new CampaignGenerator workspace."
    )
    parser.add_argument(
        "path",
        help="Directory to create the workspace in (e.g. ~/campaigns/icespire)",
    )
    parser.add_argument(
        "--name", "-n",
        default=None,
        help="Campaign name, used in placeholder file headers (default: directory name)",
    )
    parser.add_argument(
        "--world-state",
        metavar="FILE",
        help="Existing world-state / lore file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--mechanics",
        metavar="FILE",
        help="Existing mechanics file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--planning",
        metavar="FILE",
        help="Existing planning file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--party",
        metavar="FILE",
        help="Existing party file to use instead of creating a placeholder",
    )
    args = parser.parse_args()

    workspace = Path(args.path).expanduser().resolve()
    name = args.name or workspace.name

    if workspace.exists() and any(workspace.iterdir()):
        print(f"Error: '{workspace}' already exists and is not empty.", file=sys.stderr)
        sys.exit(1)

    docs_dir = workspace / "docs"
    logs_dir = workspace / "logs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    # Resolve each doc: use supplied path or create a placeholder
    if args.world_state:
        world_state_path = resolve_existing("--world-state", args.world_state)
        world_state_note = f"← {world_state_path}"
    else:
        world_state_path = placeholder(docs_dir, "world_state.md",
                                       WORLD_STATE_TEMPLATE.format(name=name))
        world_state_note = "← paste your lore here"

    if args.mechanics:
        mechanics_path = resolve_existing("--mechanics", args.mechanics)
        mechanics_note = f"← {mechanics_path}"
    else:
        mechanics_path = placeholder(docs_dir, "mechanics.md",
                                     MECHANICS_TEMPLATE.format(name=name))
        mechanics_note = "← arc scores, house rules"

    if args.planning:
        planning_path = resolve_existing("--planning", args.planning)
        planning_note = f"← {planning_path}"
    else:
        planning_path = placeholder(docs_dir, "planning.md",
                                    PLANNING_TEMPLATE.format(name=name))
        planning_note = "← enemy dossiers, NPC notes"

    if args.party:
        party_path = resolve_existing("--party", args.party)
        party_note = f"← {party_path}"
    else:
        party_path = placeholder(docs_dir, "party.md",
                                 PARTY_TEMPLATE.format(name=name))
        party_note = "← current party roster and arc scores"

    # Write config.yaml
    config_content = CONFIG_TEMPLATE.format(
        system_prompt=SCRIPT_DIR / "config" / "system_prompt.md",
        log_dir=logs_dir,
        lore_oracle=SCRIPT_DIR / "config" / "agents" / "lore_oracle.md",
        encounter_architect=SCRIPT_DIR / "config" / "agents" / "encounter_architect.md",
        voice_keeper=SCRIPT_DIR / "config" / "agents" / "voice_keeper.md",
        world_state=world_state_path,
        mechanics=mechanics_path,
        planning=planning_path,
        party=party_path,
    )
    config_path = workspace / "config.yaml"
    config_path.write_text(config_content, encoding="utf-8")

    # Summary
    print(f"\nWorkspace created: {workspace}")
    print(f"\n  {workspace}/")
    print(f"  ├── config.yaml")
    if not args.world_state or not args.mechanics or not args.planning:
        print(f"  ├── docs/")
        if not args.world_state:
            print(f"  │   ├── world_state.md   {world_state_note}")
        if not args.mechanics:
            print(f"  │   ├── mechanics.md     {mechanics_note}")
        if not args.planning:
            print(f"  │   ├── planning.md      {planning_note}")
        if not args.party:
            print(f"  │   └── party.md         {party_note}")
    if args.world_state:
        print(f"  │   world_state  →  {world_state_path}")
    if args.mechanics:
        print(f"  │   mechanics    →  {mechanics_path}")
    if args.planning:
        print(f"  │   planning     →  {planning_path}")
    if args.party:
        print(f"  │   party        →  {party_path}")
    print(f"  └── logs/               ← auto-generated session logs")
    print(f"\nNext steps:")
    if not (args.world_state and args.mechanics and args.planning):
        print(f"  1. Fill in any placeholder docs/ files with your campaign content")
    print(f"  2. Run prep from anywhere:")
    print(f"     python {SCRIPT_DIR}/prep.py --config {config_path} --beat \"...\"")
    print(f"     python {SCRIPT_DIR}/npc_table.py --config {config_path}")
    print()


if __name__ == "__main__":
    main()
