"""Shared fixtures.

``fixture_workspace`` points at ``tests/fixtures/provenance/`` — a **pinned**
two-campaign workspace, not a copy of the live one.

That is deliberate and it cost something to learn. Two of spec Story 2's
acceptance Givens are already false on the live corpus (research D11), and the
live corpus is regenerated by pipelines that move text out from under an
assertion: incident 1's stale sentence was regenerated away between the spec
being written and 2026-08-05 (research D12). A contract test asserting a
mechanism against a corpus that rewrites itself does not fail when the mechanism
breaks — it fails on a Tuesday when someone runs ``distill``, and gets muted.

So: mechanism assertions run here, where nothing drifts. Live-corpus assertions
are separate and skip cleanly when ``~/src/campaigns`` is absent.
"""

from __future__ import annotations

from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_WORKSPACE = REPO_ROOT / "tests" / "fixtures" / "provenance"


@pytest.fixture(scope="session")
def fixture_workspace() -> Path:
    assert FIXTURE_WORKSPACE.is_dir(), f"pinned fixture workspace missing: {FIXTURE_WORKSPACE}"
    return FIXTURE_WORKSPACE


@pytest.fixture(scope="session")
def fixture_manifest(fixture_workspace: Path):
    from provenance.manifest import load_manifest

    return load_manifest(fixture_workspace / "provenance.yaml")


@pytest.fixture(scope="session")
def alpha(fixture_manifest):
    """The full-featured fixture campaign — all four tiers, overlaps, corrections."""
    return fixture_manifest.campaigns["alpha"]


@pytest.fixture(scope="session")
def beta(fixture_manifest):
    """The deliberately impoverished one — no identity store, no horizon, no corrections."""
    return fixture_manifest.campaigns["beta"]
