"""Shared fixtures.

``fixture_workspace`` points at ``tests/fixtures/provenance/`` — a **pinned**
two-campaign workspace, not a copy of the live one.

That is deliberate and it cost something to learn. Two of spec Story 2's
acceptance Givens are already false on the live corpus (research D11), and the
live corpus is regenerated by pipelines that move text out from under an
assertion: incident 1's stale sentence was regenerated away between the spec
being written and 2026-08-05 (research D12). A contract test asserting a
mechanism against a corpus that rewrites itself does not fail when the mechanism
breaks — it fails on a Tuesday when someone runs ``distill``, and gets muted.

So: mechanism assertions run here, where nothing drifts. Live-corpus assertions
are separate and skip cleanly when ``~/src/campaigns`` is absent.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_WORKSPACE = REPO_ROOT / "tests" / "fixtures" / "provenance"

# The suite must import the tree it lives in.
#
# pytest's `prepend` import mode only puts `tests/` (and `tests/benchmarks/`) on
# sys.path, the venv's `pytest` entry point does not put the cwd there, and the
# editable install's .pth points at /home/kroussos/src/CampaignGenerator. So
# inside a git worktree, any module that does not insert the repo root itself
# imports the MAIN checkout — and once one has (tests/benchmarks/ is collected
# first and does exactly that), sys.modules is poisoned for everything after it.
# A whole-suite run then reports green against code the branch never touched.
#
# conftest is imported before any test module, so doing it once here closes that
# for all of them. In the main checkout this is a no-op: the .pth already put
# that same path on sys.path.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


@pytest.fixture(scope="session")
def fixture_workspace() -> Path:
    assert FIXTURE_WORKSPACE.is_dir(), f"pinned fixture workspace missing: {FIXTURE_WORKSPACE}"
    return FIXTURE_WORKSPACE


@pytest.fixture(scope="session")
def fixture_manifest(fixture_workspace: Path):
    from provenance.manifest import load_manifest

    return load_manifest(fixture_workspace / "provenance.yaml")


@pytest.fixture(scope="session")
def alpha(fixture_manifest):
    """The full-featured fixture campaign — all four tiers, overlaps, corrections."""
    return fixture_manifest.campaigns["alpha"]


@pytest.fixture(scope="session")
def beta(fixture_manifest):
    """The deliberately impoverished one — no identity store, no horizon, no corrections."""
    return fixture_manifest.campaigns["beta"]


# ── the live corpus ──────────────────────────────────────────────────────────
#
# Skipped, never failed, when the workspace is absent. CI and a fresh clone have
# no ~/src/campaigns, and a suite that goes red there would train everyone to
# ignore it (T096).


def _live_root() -> Path:
    from provenance.manifest import resolve_workspace_root

    return resolve_workspace_root(None).path


@pytest.fixture(scope="session")
def live_workspace() -> Path:
    root = _live_root()
    if not (root / "provenance.yaml").is_file():
        pytest.skip(f"live workspace absent: no manifest at {root / 'provenance.yaml'}")
    return root


@pytest.fixture(scope="session")
def live_manifest(live_workspace: Path):
    from provenance.manifest import load_manifest

    return load_manifest(live_workspace / "provenance.yaml")


@pytest.fixture(scope="session")
def rg_or_skip():
    """The rg-specific tests are skipped, not failed, on a host without it."""
    import shutil

    if shutil.which("rg") is None:
        pytest.skip("ripgrep is not on PATH; the rg scanner cannot be exercised here")
    return shutil.which("rg")


# ── Credentials ─────────────────────────────────────────────────────────────

#: Obviously not a real key, and never used for a call. Named so that if it
#: ever escapes into an error message or a recorded argv, it reads as a test
#: artifact rather than as a redacted secret.
DUMMY_ANTHROPIC_KEY = "sk-ant-dummy-for-tests"


@pytest.fixture(autouse=True)
def _dummy_anthropic_key(monkeypatch):
    """Give every test a credential, so no test fails for the shell's lack of one.

    28 tests across five files failed purely because `ANTHROPIC_API_KEY` was not
    exported in the shell running pytest (#426). They already mock the client —
    they assert retry logic, truncation banners, batch polling and progress
    output — but not far enough up to clear the metered-API refusal in
    `campaignlib/api/client.py`. So a keyless machine reported failures nobody
    caused, and the habit becomes run -> see red -> re-run or ignore. This file
    already refuses to do that to people, twice, in its own words:

        a suite that goes red there would train everyone to ignore it (T096)

    **The refusal being cleared is deliberate and is not weakened** (#342). Each
    backend still refuses for itself, at the call, and
    `tests/test_no_credential_gate.py` still fails the build if a global "is a
    key set" probe reappears. Nothing here reaches the network: no test can make
    a metered call with this value.

    Autouse rather than the per-test fixture #426 sketched. The issue's own
    follow-up asks for "a guard so this cannot regress — otherwise the next test
    to reach a live client object silently rejoins the 28", and a default no test
    has to remember *is* that guard, structurally, instead of a second test that
    has to enumerate the first one's blind spot. Skipping was rejected for the
    reason the issue gives: these are real assertions and should run everywhere.

    A test that cares about absence deletes it, which is already the established
    pattern — `monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)`, used at
    five sites today, four of them in the #342 guard itself. Function-scoped
    monkeypatch means a test's own `setenv`/`delenv` runs after this and wins.
    """
    monkeypatch.setenv("ANTHROPIC_API_KEY", DUMMY_ANTHROPIC_KEY)
