"""Shared fixtures.

``fixture_workspace`` points at ``tests/fixtures/provenance/`` — a **pinned**
two-campaign workspace, not a copy of the live one.

That is deliberate and it cost something to learn. Two of spec Story 2's
acceptance Givens are already false on the live corpus (research D11), and the
live corpus is regenerated by pipelines that move text out from under an
assertion: incident 1's stale sentence was regenerated away between the spec
being written and 2026-08-05 (research D12). A contract test asserting a
mechanism against a corpus that rewrites itself does not fail when the mechanism
breaks — it fails on a Tuesday when someone runs ``distill``, and gets muted.

So: mechanism assertions run here, where nothing drifts. Live-corpus assertions
are separate and skip cleanly when ``~/src/campaigns`` is absent.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
FIXTURE_WORKSPACE = REPO_ROOT / "tests" / "fixtures" / "provenance"

# The suite must import the tree it lives in.
#
# pytest's `prepend` import mode only puts `tests/` (and `tests/benchmarks/`) on
# sys.path, the venv's `pytest` entry point does not put the cwd there, and the
# editable install's .pth points at /home/kroussos/src/CampaignGenerator. So
# inside a git worktree, any module that does not insert the repo root itself
# imports the MAIN checkout — and once one has (tests/benchmarks/ is collected
# first and does exactly that), sys.modules is poisoned for everything after it.
# A whole-suite run then reports green against code the branch never touched.
#
# conftest is imported before any test module, so doing it once here closes that
# for all of them. In the main checkout this is a no-op: the .pth already put
# that same path on sys.path.
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))


@pytest.fixture(scope="session")
def fixture_workspace() -> Path:
    assert FIXTURE_WORKSPACE.is_dir(), f"pinned fixture workspace missing: {FIXTURE_WORKSPACE}"
    return FIXTURE_WORKSPACE


@pytest.fixture(scope="session")
def fixture_manifest(fixture_workspace: Path):
    from provenance.manifest import load_manifest

    return load_manifest(fixture_workspace / "provenance.yaml")


@pytest.fixture(scope="session")
def alpha(fixture_manifest):
    """The full-featured fixture campaign — all four tiers, overlaps, corrections."""
    return fixture_manifest.campaigns["alpha"]


@pytest.fixture(scope="session")
def beta(fixture_manifest):
    """The deliberately impoverished one — no identity store, no horizon, no corrections."""
    return fixture_manifest.campaigns["beta"]


# ── the live corpus ──────────────────────────────────────────────────────────
#
# Skipped, never failed, when the workspace is absent. CI and a fresh clone have
# no ~/src/campaigns, and a suite that goes red there would train everyone to
# ignore it (T096).


def _live_root() -> Path:
    from provenance.manifest import resolve_workspace_root

    return resolve_workspace_root(None).path


@pytest.fixture(scope="session")
def live_workspace() -> Path:
    root = _live_root()
    if not (root / "provenance.yaml").is_file():
        pytest.skip(f"live workspace absent: no manifest at {root / 'provenance.yaml'}")
    return root


@pytest.fixture(scope="session")
def live_manifest(live_workspace: Path):
    from provenance.manifest import load_manifest

    return load_manifest(live_workspace / "provenance.yaml")


@pytest.fixture(scope="session")
def rg_or_skip():
    """The rg-specific tests are skipped, not failed, on a host without it."""
    import shutil

    if shutil.which("rg") is None:
        pytest.skip("ripgrep is not on PATH; the rg scanner cannot be exercised here")
    return shutil.which("rg")
