"""Snapshot test for session_doc.py's externalised prompts.

This test guards against byte-level drift in the shared narration-v1 brief,
its campaign/style wrappers, and the other externalised session prompts.
Intentional prompt changes require review and explicit golden regeneration.

The golden lives at tests/golden/prompts/narrate_system_matrix.json
and was generated by walking the full flag matrix of
build_narrate_system plus every standalone constant and the
PREV_VOICE_CONTRAST branch of build_narrate_prompt.

To regenerate the golden (when a prompt edit is intended):

    rm tests/golden/prompts/narrate_system_matrix.json
    python -m pytest tests/test_session_doc_prompts.py
        (test fails and writes a fresh golden — re-run to confirm green)
"""
import json
import os
import sys
from collections.abc import Mapping
from pathlib import Path
from types import MappingProxyType

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import session_doc  # noqa: E402

GOLDEN = Path(__file__).resolve().parent / "golden" / "prompts" / "narrate_system_matrix.json"

# Fixture values — must match the script that generated the golden.
EXAMPLES = "Once upon a time in Phandalin a brave druid faced a manticore..."
CHAR_EX  = "Brewbarry whittled a stick, eyes on the door, saying nothing for once."
VOICE_NOTE = "Brewbarry speaks in short clipped lines. Dry humour. No exclamation points."
NARRATOR = "Brewbarry"


def _build_matrix() -> dict[str, str]:
    flags = []
    for examples_text in (None, EXAMPLES):
        for scene in (None, "The Wave Echo Chamber"):
            for prose_mode in (False, True):
                for has_scene_events in (False, True):
                    for scene_anchored in (False, True):
                        for char_examples in (None, CHAR_EX):
                            for voice_note in (None, VOICE_NOTE):
                                for genre in (None, "First-person noir fantasy memoir"):
                                    flags.append({
                                        "examples_text": examples_text,
                                        "scene": scene,
                                        "prose_mode": prose_mode,
                                        "has_scene_events": has_scene_events,
                                        "scene_anchored": scene_anchored,
                                        "narrator": NARRATOR,
                                        "char_examples": char_examples,
                                        "voice_note": voice_note,
                                        "genre": genre,
                                    })

    def label(f):
        return (
            f"ex{int(f['examples_text'] is not None)}"
            f"_sc{int(f['scene'] is not None)}"
            f"_pm{int(f['prose_mode'])}"
            f"_se{int(f['has_scene_events'])}"
            f"_sa{int(f['scene_anchored'])}"
            f"_ce{int(f['char_examples'] is not None)}"
            f"_vn{int(f['voice_note'] is not None)}"
            f"_gn{int(f['genre'] is not None)}"
        )

    matrix = {label(f): session_doc.build_narrate_system(**f) for f in flags}
    matrix["__CONSISTENCY_SYSTEM"]        = session_doc.CONSISTENCY_SYSTEM
    matrix["__PLAN_SYSTEM"]               = session_doc.PLAN_SYSTEM
    matrix["__DIALOGUE_INSTRUCTION_FULL"] = session_doc.DIALOGUE_INSTRUCTION_FULL
    matrix["__DIALOGUE_INSTRUCTION_COND"] = session_doc.DIALOGUE_INSTRUCTION_CONDITIONAL
    matrix["__PROSE_MODE_INSTRUCTION"]    = session_doc.PROSE_MODE_INSTRUCTION
    matrix["__AUDIT_HATCH_INSTRUCTION"]   = session_doc.AUDIT_HATCH_INSTRUCTION
    matrix["__NAME_FIDELITY_INSTRUCTION"] = session_doc.NAME_FIDELITY_INSTRUCTION
    matrix["__REAL_NAMES_INSTRUCTION"] = session_doc.REAL_NAMES_INSTRUCTION
    matrix["__PREV_VOICE_CONTRAST_via_prompt"] = session_doc.build_narrate_prompt(
        narrator="Brewbarry",
        focus="Whittle and watch.",
        char_moments="- He whittles. He watches.",
        party="## Brewbarry\n**Halfling Rogue 5, Player: Sam**",
        handoff="",
        roster="- Brewbarry (Sam): Halfling Rogue 5",
        prev_narrator="Soma",
        prev_voice_sample="The wind tasted of salt and old grief.",
    )
    return matrix


@pytest.fixture(scope="module")
def matrix() -> Mapping[str, str]:
    """The whole flag matrix, built once for the six tests that read it (#405).

    Every test in this file wants the same 265 entries, and each used to call
    `_build_matrix()` for itself. Module scope rather than a module-level
    constant so a run that selects none of them (`-k` elsewhere) builds nothing,
    and so an exception during construction is reported as a fixture error
    against the tests that needed it rather than as a collection failure for the
    file.

    Read-only by construction: one shared dict across tests is only safe while
    nothing writes to it, and `mappingproxy` makes that a property of the object
    instead of a convention six tests have to keep. Nothing needs to write —
    `_build_matrix` does all its assembly internally and hands back a finished
    dict — so the only cost is `dict()` at the one place that re-serialises it.
    """
    return MappingProxyType(_build_matrix())


def test_the_shared_matrix_cannot_be_mutated_by_a_test(matrix):
    """#405 traded six private builds for one shared object; this is the guard.

    Six tests reading one dict is only equivalent to six building their own
    while none of them writes. Enforced rather than asked for, because a write
    would not fail here — it would surface as a different test failing later,
    in an order-dependent way, with nothing pointing back at the writer.
    """
    with pytest.raises(TypeError):
        matrix["__injected_by_a_test"] = "x"
    assert "__injected_by_a_test" not in matrix


def test_prompt_matrix_matches_golden(matrix):
    """Every build_narrate_system flag combo + every standalone constant
    must produce byte-identical output to the reviewed golden."""
    current = matrix

    if not GOLDEN.exists() or os.environ.get("UPDATE_PROMPT_GOLDEN") == "1":
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(json.dumps(dict(current), indent=2, sort_keys=True),
                          encoding="utf-8")
        pytest.fail(
            f"Golden {'regenerated' if GOLDEN.exists() else 'written'}: "
            f"{GOLDEN}. Re-run the test to verify green."
        )

    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))

    missing_keys = set(expected) - set(current)
    extra_keys   = set(current) - set(expected)
    assert not missing_keys, f"matrix missing keys: {sorted(missing_keys)[:5]}"
    assert not extra_keys,   f"matrix has extra keys: {sorted(extra_keys)[:5]}"

    diffs = [k for k in expected if expected[k] != current[k]]
    if diffs:
        # Show the first byte-level diff to help debugging.
        k = diffs[0]
        exp = expected[k]
        got = current[k]
        for i, (a, b) in enumerate(zip(exp, got)):
            if a != b:
                ctx_start = max(0, i - 40)
                ctx_end = min(len(exp), i + 40)
                pytest.fail(
                    f"{len(diffs)} matrix entries diverged from golden. "
                    f"First: {k!r} at offset {i}\n"
                    f"  expected: ...{exp[ctx_start:ctx_end]!r}...\n"
                    f"  actual:   ...{got[ctx_start:ctx_end]!r}..."
                )
        pytest.fail(
            f"{len(diffs)} entries diverged from golden (length mismatch). "
            f"First: {k!r} (expected {len(exp)} chars, got {len(got)} chars)"
        )


def test_every_narration_mode_uses_v1_without_conflicting_legacy_rules(matrix):
    """A golden refresh must not hide an old wrapper undoing the new brief."""
    from session_doc.narrate import NARRATION_WRITING_BRIEF

    for mode, prompt in matrix.items():
        if mode.startswith("__"):
            continue
        assert prompt.count(NARRATION_WRITING_BRIEF.strip()) == 1, mode
        assert "close first-person voice" in prompt, mode
        assert "Preserve what remains unknown" in prompt, mode
        for obsolete in (
            "Target 600-900 words", "2-3 sentences", "typically 4–8",
            "every line should appear", "THE DIALOGUE IS THE STORY",
            "No mechanical numbers",
            "they were there",
            # #408/#410/#411 — retired verbatim-dialogue and destructive-rewrite
            # wording, replaced by the adaptation-licensed brief and the
            # unconditional name-fidelity rule.
            "Use the speakers' actual wording for retained dialogue",
            "DO NOT invent or paraphrase",
            "verbatim record",
            "Never alter words inside quotation marks",
            "Never apply them inside quotation marks",
            "preserve the spoken words",
            "Verbatim Quotes",
            "preserve retained spoken words",
            "preserving the source wording",
            "grounded in the supplied lines",
        ):
            assert obsolete not in prompt, (mode, obsolete)


def test_every_narration_mode_carries_the_table_speech_audit_hatch(matrix):
    """#396, across the whole flag matrix.

    `26ec5b0` deleted the hatch from `prose_mode.md` and banned it in
    `writing_brief.md`, but kept the reclassification judgment — which lives in
    the always-on brief (¶6, "Table instructions, mechanical procedure, and
    editorial notes are not spoken dialogue"), not in prose mode. So the record
    has to reach every mode the judgment reaches, and the pre-26ec5b0 design,
    which carried it only in `prose_mode.md` and `dialogue_conditional.md`,
    would fail this walk too.
    """
    for mode, prompt in matrix.items():
        if mode.startswith("__"):
            continue
        assert "table-speech reclassified" in prompt, mode
        assert "the GM's review queue" in prompt, mode
        # The narrow scope is the load-bearing half: #386 ruled that coverage
        # of ordinary editorial omission belongs in a separate review pass, so
        # an audit that logged omitted filler would be the wrong feature.
        assert "never listed here" in prompt, mode
        # Honesty about self-flagging — `ExtractionContract_proposal.md`'s
        # "Why the model is not the flagger" measured both #245 arms missing
        # the same span, so an empty hatch must never read as a clean scene.
        assert "not a claim of completeness" in " ".join(prompt.split()), mode


def test_every_narration_mode_carries_the_name_fidelity_rule(matrix):
    """#410/#411, across the whole flag matrix.

    The old anti-normalization caveat (#223) lived only inside the `if
    npc_roster:` block, so a scene with no NPC roster — a new campaign, or a
    scene where nothing in `docs/npcs/` matched — got no rule at all: nothing
    to stop the model from "correcting" a name inside a quoted line the moment
    an alias registry existed anywhere else in the prompt. #411 moved the rule
    out of that conditional and into `{name_fidelity}` in both `base.md` and
    `bundle_base.md`, so it is now unconditional on both render paths — it does
    not depend on having a canonical spellings list to normalize *toward*,
    because it is a rule about characterization — the name a speaker chose is
    part of what the line reveals about them — not a spelling-hygiene rule.
    """
    for mode, prompt in matrix.items():
        if mode.startswith("__"):
            continue
        flat = " ".join(prompt.split())
        assert "NAMES INSIDE QUOTED SPEECH" in prompt, mode
        assert "characterization, not a spelling error" in prompt, mode
        assert "Never normalize a name inside a quoted line" in flat, mode


def test_every_narration_mode_carries_the_real_names_rule(matrix):
    """#398, across the whole flag matrix.

    `26ec5b0` deleted the rule forbidding real players'/the GM's names in
    narration prose from `prose_mode.md` and replaced it with nothing — no
    other file picked it up. Nothing caught the gap because that same commit
    regenerated the golden this test's sibling relies on, so the golden
    baked in the rule's absence instead of catching it. The rule is restored
    as its own template, `real_names.md`, reached by a `{real_names}`
    placeholder in both `base.md` and `bundle_base.md` — unconditional on
    both render paths, the same structure #411 used for `name_fidelity.md`.
    """
    for mode, prompt in matrix.items():
        if mode.startswith("__"):
            continue
        flat = " ".join(prompt.split())
        assert "THE PEOPLE AT THE TABLE" in prompt, mode
        assert "their real names never appear in the prose" in flat, mode
        assert "Only the characters exist in the fiction" in flat, mode
        assert "does not receive information from a person at the table" in flat, mode


def test_no_narration_mode_lets_the_brief_outrank_the_campaign_on_tense(matrix):
    """#395, across the whole flag matrix.

    Tense reached the model from four templates (`writing_brief`, `base`,
    `bundle_base`, `voice_spec`) and one f-string in `narrate.py`. Fixing the
    brief alone leaves the precedence blocks still saying it wins, so this
    walks every combination rather than the one the fix was written against.
    """
    for mode, prompt in matrix.items():
        if mode.startswith("__"):
            continue
        assert "present-tense voice" not in prompt, mode
        assert "knowledge boundaries, tense" not in prompt, mode
        assert "diction and register only" not in prompt, mode
        assert "the campaign's tense" in prompt, mode
        assert "the authority on tense" in prompt, mode
        # Only the modes carrying a rulebook emit the tail reminder that
        # repeats it with recency, which is the copy small local models read.
        if mode.endswith("_gn1"):
            assert "diction, register, and tense" in prompt, mode
