"""Snapshot test for session_doc.py's externalised prompts.

This test guards against byte-level drift in the shared narration-v1 brief,
its campaign/style wrappers, and the other externalised session prompts.
Intentional prompt changes require review and explicit golden regeneration.

The golden lives at tests/golden/prompts/narrate_system_matrix.json
and was generated by walking the full flag matrix of
build_narrate_system plus every standalone constant and the
PREV_VOICE_CONTRAST branch of build_narrate_prompt.

To regenerate the golden (when a prompt edit is intended):

    rm tests/golden/prompts/narrate_system_matrix.json
    python -m pytest tests/test_session_doc_prompts.py
        (test fails and writes a fresh golden — re-run to confirm green)
"""
import json
import os
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import session_doc  # noqa: E402

GOLDEN = Path(__file__).resolve().parent / "golden" / "prompts" / "narrate_system_matrix.json"

# Fixture values — must match the script that generated the golden.
EXAMPLES = "Once upon a time in Phandalin a brave druid faced a manticore..."
CHAR_EX  = "Brewbarry whittled a stick, eyes on the door, saying nothing for once."
VOICE_NOTE = "Brewbarry speaks in short clipped lines. Dry humour. No exclamation points."
NARRATOR = "Brewbarry"


def _build_matrix() -> dict[str, str]:
    flags = []
    for examples_text in (None, EXAMPLES):
        for scene in (None, "The Wave Echo Chamber"):
            for prose_mode in (False, True):
                for has_scene_events in (False, True):
                    for scene_anchored in (False, True):
                        for char_examples in (None, CHAR_EX):
                            for voice_note in (None, VOICE_NOTE):
                                for genre in (None, "First-person noir fantasy memoir"):
                                    flags.append({
                                        "examples_text": examples_text,
                                        "scene": scene,
                                        "prose_mode": prose_mode,
                                        "has_scene_events": has_scene_events,
                                        "scene_anchored": scene_anchored,
                                        "narrator": NARRATOR,
                                        "char_examples": char_examples,
                                        "voice_note": voice_note,
                                        "genre": genre,
                                    })

    def label(f):
        return (
            f"ex{int(f['examples_text'] is not None)}"
            f"_sc{int(f['scene'] is not None)}"
            f"_pm{int(f['prose_mode'])}"
            f"_se{int(f['has_scene_events'])}"
            f"_sa{int(f['scene_anchored'])}"
            f"_ce{int(f['char_examples'] is not None)}"
            f"_vn{int(f['voice_note'] is not None)}"
            f"_gn{int(f['genre'] is not None)}"
        )

    matrix = {label(f): session_doc.build_narrate_system(**f) for f in flags}
    matrix["__CONSISTENCY_SYSTEM"]        = session_doc.CONSISTENCY_SYSTEM
    matrix["__PLAN_SYSTEM"]               = session_doc.PLAN_SYSTEM
    matrix["__DIALOGUE_INSTRUCTION_FULL"] = session_doc.DIALOGUE_INSTRUCTION_FULL
    matrix["__DIALOGUE_INSTRUCTION_COND"] = session_doc.DIALOGUE_INSTRUCTION_CONDITIONAL
    matrix["__PROSE_MODE_INSTRUCTION"]    = session_doc.PROSE_MODE_INSTRUCTION
    matrix["__PREV_VOICE_CONTRAST_via_prompt"] = session_doc.build_narrate_prompt(
        narrator="Brewbarry",
        focus="Whittle and watch.",
        char_moments="- He whittles. He watches.",
        party="## Brewbarry\n**Halfling Rogue 5, Player: Sam**",
        handoff="",
        roster="- Brewbarry (Sam): Halfling Rogue 5",
        prev_narrator="Soma",
        prev_voice_sample="The wind tasted of salt and old grief.",
    )
    return matrix


def test_prompt_matrix_matches_golden():
    """Every build_narrate_system flag combo + every standalone constant
    must produce byte-identical output to the reviewed golden."""
    current = _build_matrix()

    if not GOLDEN.exists() or os.environ.get("UPDATE_PROMPT_GOLDEN") == "1":
        GOLDEN.parent.mkdir(parents=True, exist_ok=True)
        GOLDEN.write_text(json.dumps(current, indent=2, sort_keys=True),
                          encoding="utf-8")
        pytest.fail(
            f"Golden {'regenerated' if GOLDEN.exists() else 'written'}: "
            f"{GOLDEN}. Re-run the test to verify green."
        )

    expected = json.loads(GOLDEN.read_text(encoding="utf-8"))

    missing_keys = set(expected) - set(current)
    extra_keys   = set(current) - set(expected)
    assert not missing_keys, f"matrix missing keys: {sorted(missing_keys)[:5]}"
    assert not extra_keys,   f"matrix has extra keys: {sorted(extra_keys)[:5]}"

    diffs = [k for k in expected if expected[k] != current[k]]
    if diffs:
        # Show the first byte-level diff to help debugging.
        k = diffs[0]
        exp = expected[k]
        got = current[k]
        for i, (a, b) in enumerate(zip(exp, got)):
            if a != b:
                ctx_start = max(0, i - 40)
                ctx_end = min(len(exp), i + 40)
                pytest.fail(
                    f"{len(diffs)} matrix entries diverged from golden. "
                    f"First: {k!r} at offset {i}\n"
                    f"  expected: ...{exp[ctx_start:ctx_end]!r}...\n"
                    f"  actual:   ...{got[ctx_start:ctx_end]!r}..."
                )
        pytest.fail(
            f"{len(diffs)} entries diverged from golden (length mismatch). "
            f"First: {k!r} (expected {len(exp)} chars, got {len(got)} chars)"
        )


def test_every_narration_mode_uses_v1_without_conflicting_legacy_rules():
    """A golden refresh must not hide an old wrapper undoing the new brief."""
    from session_doc.narrate import NARRATION_WRITING_BRIEF

    for mode, prompt in _build_matrix().items():
        if mode.startswith("__"):
            continue
        assert prompt.count(NARRATION_WRITING_BRIEF.strip()) == 1, mode
        assert "close first-person voice" in prompt, mode
        assert "Preserve what remains unknown" in prompt, mode
        for obsolete in (
            "Target 600-900 words", "2-3 sentences", "typically 4–8",
            "every line should appear", "THE DIALOGUE IS THE STORY",
            "No mechanical numbers", "table-speech reclassified",
            "they were there",
        ):
            assert obsolete not in prompt, (mode, obsolete)


def test_no_narration_mode_lets_the_brief_outrank_the_campaign_on_tense():
    """#395, across the whole flag matrix.

    Tense reached the model from four templates (`writing_brief`, `base`,
    `bundle_base`, `voice_spec`) and one f-string in `narrate.py`. Fixing the
    brief alone leaves the precedence blocks still saying it wins, so this
    walks every combination rather than the one the fix was written against.
    """
    for mode, prompt in _build_matrix().items():
        if mode.startswith("__"):
            continue
        assert "present-tense voice" not in prompt, mode
        assert "knowledge boundaries, tense" not in prompt, mode
        assert "diction and register only" not in prompt, mode
        assert "the campaign's tense" in prompt, mode
        assert "the authority on tense" in prompt, mode
        # Only the modes carrying a rulebook emit the tail reminder that
        # repeats it with recency, which is the copy small local models read.
        if mode.endswith("_gn1"):
            assert "diction, register, and tense" in prompt, mode
