"""Tests for session_doc/vtt_voice_compare.py's `speaker_pairs` reader (#263).

`speaker_pairs` replaced a private regex scan (renamed from `parse_vtt`,
which collided with the unrelated `session_doc.io.parse_vtt`) that had no
NOTE rule and read any colon-bearing line as dialogue. That defect is why
`campaignlib.vtt.render` used to refuse a generated NOTE line containing a
colon — a live generator crippled to work around a single-caller analysis
tool's bug. `speaker_pairs` now delegates to `campaignlib.vtt.parse`, which
already separates NOTE blocks from cues, so the guard could be deleted.
This file is the proof the rewire works.
"""

import sys
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO_ROOT))

import campaignlib  # noqa: E402

# See tests/test_locate_quote_parity.py for why this guard exists.
_resolved = Path(campaignlib.__file__).resolve().parent.parent
if _resolved != _REPO_ROOT:
    pytest.skip(
        f"campaignlib resolved to {_resolved}, not this worktree ({_REPO_ROOT}).",
        allow_module_level=True,
    )

from campaignlib.vtt import VttError, parse, render  # noqa: E402
from session_doc.vtt_voice_compare import speaker_pairs  # noqa: E402

RAW = """WEBVTT

1
00:00:01.000 --> 00:00:04.000
Gary Young: I mean, the town has been protected by the strength of the pandemic.

2
00:00:05.000 --> 00:00:08.000
Kostadis Roussos: Alright, Brynn and Giles are actually in the temple.
"""


def test_generated_note_with_a_colon_does_not_leak_in_as_a_speaker():
    """The rewire's proof: a generated NOTE containing a colon must not be
    read as dialogue, now that render's colon guard is gone."""
    out = render(parse(RAW), ["NOTE generated by: cg"])
    pairs = speaker_pairs(out)
    speakers = {s for s, _ in pairs}
    assert "NOTE generated by" not in speakers
    assert len(pairs) == 2
    assert speakers == {"Gary Young", "Kostadis Roussos"}


def test_speaker_pairs_raises_on_a_headerless_fragment():
    """No WEBVTT header — `campaignlib.vtt.parse` refuses rather than
    guessing, and `speaker_pairs` must propagate that refusal, not fall
    back to a private scan."""
    with pytest.raises(VttError, match="not a WebVTT"):
        speaker_pairs("1\n00:00:01.000 --> 00:00:02.000\nGary Young: hi\n")


def test_speaker_pairs_raises_on_two_headers_concatenated():
    """Two recordings joined into one file — the other real-tape defect this
    reader must not silently paper over. A blank line separates them, as it
    would when two complete VTT files (each already blank-line-terminated)
    are concatenated on disk."""
    concatenated = RAW + "\n" + RAW
    with pytest.raises(VttError):
        speaker_pairs(concatenated)
