<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useConfigStore } from '../../stores/config'
import PathField from '../../components/shared/PathField.vue'
import RunPanel from '../../components/shared/RunPanel.vue'

const config = useConfigStore()

const input = ref('')
const output = ref('')
const trackFile = ref('')
const trackInline = ref('')
const extractDir = ref('')
const chunkSize = ref(60000)
const synthOnly = ref(false)
const noLog = ref(false)
const showAdvanced = ref(false)

function loadFromConfig() {
  const v = config.values
  input.value = v.cs_input || v.summaries || ''
  output.value = v.cs_output || v.campaign_state_output || ''
  trackFile.value = v.cs_track_file || v.tracking_file || ''
  extractDir.value = v.cs_extract_dir || ''
  chunkSize.value = v.cs_chunk_size || 60000
}

const ready = computed(() => {
  if (synthOnly.value) return !!output.value.trim()
  return !!(input.value.trim() && output.value.trim())
})

const trackItems = computed(() =>
  trackInline.value.split('\n').map(l => l.trim()).filter(Boolean)
)

const runParams = computed(() => ({
  input: input.value,
  output: output.value,
  track_file: trackFile.value,
  track: trackItems.value,
  extract_dir: extractDir.value,
  chunk_size: chunkSize.value,
  synthesize_only: synthOnly.value,
  no_log: noLog.value,
  model: config.model,
}))

onMounted(() => { loadFromConfig() })
</script>

<template>
  <div class="page">
    <div class="page-header">
      <h2>Campaign State</h2>
      <p class="subtitle">
        Generate campaign_state.md &mdash; a grounding document that tells planning scripts what has been completed and what is currently true.
      </p>
    </div>

    <div class="form-grid">
      <div class="form-section">
        <div class="field">
          <label class="checkbox-label">
            <input type="checkbox" v-model="synthOnly" />
            Re-synthesize from existing extractions
          </label>
        </div>
      </div>

      <div v-if="!synthOnly" class="form-section">
        <PathField v-model="input" label="Session summaries file" required resolve-base="campaign"
          help="The large summaries.md file that gets chunked and extracted." />
      </div>

      <div class="form-section">
        <PathField v-model="output" label="Output file" required is-output resolve-base="campaign"
          help="campaign_state.md — loaded first by prep.py as grounding context." />
      </div>

      <div class="form-section">
        <PathField v-model="trackFile" label="Tracking file" resolve-base="campaign"
          help="tracking.txt — ensures specific events are never missed. Generated by make_tracking.py." />
      </div>

      <!-- Advanced -->
      <div class="form-section">
        <button class="btn-neutral btn-sm" @click="showAdvanced = !showAdvanced">
          {{ showAdvanced ? 'Hide' : 'Show' }} advanced options
        </button>

        <div v-if="showAdvanced" class="advanced-panel">
          <div class="field">
            <label class="field-label">Inline tracking items</label>
            <textarea class="field-textarea" v-model="trackInline" rows="4"
              placeholder="One item per line (in addition to tracking file)" />
          </div>
          <PathField v-model="extractDir" label="Extractions directory" resolve-base="campaign"
            help="Where intermediate state_extractions/ files are saved." />
          <div class="field">
            <label class="field-label">Chunk size (chars)</label>
            <input type="number" class="field-input" v-model.number="chunkSize" min="10000" step="5000" />
          </div>
          <div class="field">
            <label class="checkbox-label">
              <input type="checkbox" v-model="noLog" />
              Skip log file
            </label>
          </div>
        </div>
      </div>

      <RunPanel
        endpoint="/api/grounding/run/campaign-state"
        :params="runParams"
        :disabled="!ready"
        label="Run Campaign State"
        @done="() => {}"
      />
    </div>
  </div>
</template>

<style scoped>
.page { padding: 20px 24px; max-width: 700px; }
.page-header { margin-bottom: 20px; }
.page-header h2 { font-size: 16px; font-weight: 700; color: var(--text); margin-bottom: 4px; }
.subtitle { font-size: 12px; color: var(--text-muted); }

.form-grid { display: flex; flex-direction: column; gap: 16px; }
.form-section {
  padding-bottom: 12px;
  border-bottom: 1px solid var(--bg-surface0);
}
.form-section:last-child { border-bottom: none; }

.field { margin-bottom: 10px; }
.field-label {
  display: block; font-size: 11px; font-weight: 600;
  color: var(--text-sub); margin-bottom: 3px;
}
.field-input, .field-textarea {
  width: 100%; padding: 6px 8px; border-radius: 4px;
  border: 1px solid var(--bg-surface1); background: var(--bg-base);
  color: var(--text); font-family: var(--mono); font-size: 11px;
  outline: none; box-sizing: border-box;
}
.field-textarea { resize: vertical; }
.field-input:focus, .field-textarea:focus { border-color: var(--mauve); }

.checkbox-label {
  font-size: 11px; color: var(--text-sub); display: flex;
  align-items: center; gap: 6px; cursor: pointer;
}
.checkbox-label input { accent-color: var(--mauve); }

.advanced-panel {
  margin-top: 10px; padding: 10px;
  background: var(--bg-mantle); border-radius: 4px;
}
</style>
