"""One-shot migration CLI -- spec 032 FR-022a-d, Constitution XIII.

Moves a campaign's loose ``docs/npcs/*`` out of the directory that now holds only
*published* dossiers, into ``docs/npcs/distilled/`` (generated by the retired distilled
pipeline) or ``docs/npcs/authored/`` (made by a person). Two steps, the GM deciding in
between::

    python -m server.migrate_npc_dossiers --campaign-dir DIR --propose
    $EDITOR DIR/docs/npcs/migration_classification.yaml     # settle every ``unknown``
    python -m server.migrate_npc_dossiers --campaign-dir DIR --apply [--force]

``--propose`` writes ``docs/npcs/migration_classification.yaml`` and moves nothing. The
only thing it ever *decides* is ``distilled`` for a file carrying the ``source_extracts:``
frontmatter marker and for the distilled pipeline's own sidecars and state files;
everything else is ``unknown``. Git history is shown as evidence (the adding commit, later
commits, whether the file changed since) and **never** sets a disposition: commits such as
"session outputs, dossier cleanup" bundle generated and hand-made files together, so
commit wording cannot tell them apart. Every git call is read-only.

``--apply`` follows the classification file. It refuses while any entry is ``unknown``,
when the disk no longer matches the proposal (a file added, removed or edited since), or
when a target exists (unless ``--force``). Moves are ``os.replace``, byte-identical. Config
rewrites are line-level and comment-preserving, exact value only: values it does not
recognise are reported, never changed.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import subprocess
import sys
from pathlib import Path
from typing import Any

import yaml

from campaignlib.constants import config_path
from campaignlib.npc import PUBLISH_HEADER_PREFIX
from campaignlib.util import atomic_write_text

CLASSIFICATION_NAME = "migration_classification.yaml"
NPCS_REL = Path("docs") / "npcs"
DISTILLED = "distilled"
AUTHORED = "authored"
SUMMARY_NATIVE = "summary_native"
#: Subdirectories (and the record itself) that are never classified.
EXCLUDED = frozenset({DISTILLED, AUTHORED, SUMMARY_NATIVE, CLASSIFICATION_NAME})
#: Files and directories that belong to the distilled pipeline by name.
DISTILLED_STATE = frozenset({".dedup_state.json", ".sidecar_merge_state.json", "merged_sidecars"})
DISPOSITIONS = ("distilled", "authored", "unknown")

OLD_DOSSIER_DIR = "docs/npcs/"
NEW_DOSSIER_DIR = "docs/npcs/distilled/"

EXTERNAL_NOTES = (
    "~/src/campaigns/provenance.yaml: globs over docs/npcs/*.md (see the lines above if any)",
    "gm-npc-build skill: writes dossiers straight into docs/npcs/ (kostadis/campaigns#370)",
    "/dossier-merge, vtt-spell-pass and consistency-check skills: read distilled dossiers "
    "under docs/npcs/",
)
CLOSING = (
    "docs/npcs/ now holds no loose dossiers, so the gm-assistant skills see no NPCs until "
    "the hand-built ones are republished. Run: summary_native npc-publish --authored-all"
)

_FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


class MigrationError(Exception):
    """A refusal or failure; printed as ``Error: ...`` with exit 1."""


# ── scanning ────────────────────────────────────────────────────────────────

def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _tree_files(path: Path) -> list[Path]:
    return sorted(p for p in path.rglob("*") if p.is_file())


def _sha256_entry(path: Path) -> str:
    if path.is_dir():
        h = hashlib.sha256()
        for f in _tree_files(path):
            h.update(f.relative_to(path).as_posix().encode() + b"\0" + _sha256_file(f).encode() + b"\n")
        return h.hexdigest()
    return _sha256_file(path)


def _size(path: Path) -> int:
    if path.is_dir():
        return sum(f.stat().st_size for f in _tree_files(path))
    return path.stat().st_size


def _is_published(path: Path) -> bool:
    if not path.is_file() or path.suffix != ".md":
        return False
    try:
        with path.open(encoding="utf-8", errors="replace") as fh:
            return fh.readline().startswith(PUBLISH_HEADER_PREFIX)
    except OSError:
        return False


def _has_marker(path: Path) -> bool:
    """True when the frontmatter carries a ``source_extracts:`` key (the distilled marker)."""
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    m = _FRONTMATTER_RE.match(text)
    return bool(m and re.search(r"^source_extracts\s*:", m.group(1), re.MULTILINE))


def _entry_name(path: Path) -> str:
    return path.name + ("/" if path.is_dir() else "")


def scan(npcs_dir: Path) -> list[Path]:
    """Every entry directly in ``npcs_dir`` that needs a disposition, sorted by name."""
    if not npcs_dir.is_dir():
        return []
    out = []
    for p in sorted(npcs_dir.iterdir(), key=lambda q: q.name):
        if p.name in EXCLUDED or _is_published(p):
            continue
        out.append(p)
    return out


def _proposed(path: Path) -> str:
    if ".new_notes." in path.name or path.name in DISTILLED_STATE:
        return "distilled"
    if _has_marker(path):
        return "distilled"
    return "unknown"


# ── git evidence (read-only) ─────────────────────────────────────────────────

def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess | None:
    """Run a read-only git command; ``None`` when git is not runnable at all."""
    env = dict(os.environ, GIT_OPTIONAL_LOCKS="0")   # never refresh the index
    try:
        return subprocess.run(["git", *args], cwd=cwd, capture_output=True, text=True, env=env)
    except OSError:
        return None


def _in_repo(cwd: Path) -> bool:
    r = _git(cwd, "rev-parse", "--show-toplevel")
    return bool(r and r.returncode == 0)


def _git_evidence(path: Path) -> Any:
    """``'unavailable'`` outside a repository; otherwise the evidence block."""
    cwd = path.parent
    if not _in_repo(cwd):
        return "unavailable"
    follow = [] if path.is_dir() else ["--follow"]
    r = _git(cwd, "log", *follow, "--format=%H%x1f%cs%x1f%s", "--", path.name)
    if r is None or r.returncode != 0:
        return "unavailable"
    commits = []
    for line in r.stdout.splitlines():
        parts = line.split("\x1f", 2)
        if len(parts) == 3:
            commits.append({"sha": parts[0][:8], "full": parts[0], "date": parts[1], "subject": parts[2]})
    if not commits:   # untracked
        return {"added": None, "later_commits": [], "changed_since_added": False}
    added = commits[-1]
    later = [{"sha": c["sha"], "subject": c["subject"]} for c in commits[:-1]]
    d = _git(cwd, "diff", "--quiet", added["full"], "--", path.name)
    changed = bool(d and d.returncode == 1)
    return {
        "added": {"sha": added["sha"], "date": added["date"], "subject": added["subject"]},
        "later_commits": later,
        "changed_since_added": changed,
    }


def _head(npcs_dir: Path) -> str | None:
    if not npcs_dir.is_dir() or not _in_repo(npcs_dir):
        return None
    r = _git(npcs_dir, "rev-parse", "--short=8", "HEAD")
    return r.stdout.strip() if r and r.returncode == 0 and r.stdout.strip() else None


# ── propose ──────────────────────────────────────────────────────────────────

def _load_classification(path: Path) -> dict:
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except (OSError, yaml.YAMLError) as exc:
        raise MigrationError(f"{path}: cannot read the classification file ({exc.__class__.__name__}); "
                             f"re-run --propose") from None
    if not isinstance(data, dict) or not isinstance(data.get("entries"), list):
        raise MigrationError(f"{path}: malformed classification file (need a mapping with an `entries` list)")
    return data


def propose(campaign_dir: Path | str) -> Path | None:
    """Write the classification file; ``None`` (and a message) when there is nothing to classify.

    A disposition the GM already set for an entry whose content has not changed is carried
    over, so re-proposing never throws away a decision.
    """
    campaign = Path(campaign_dir).expanduser().resolve()
    npcs = campaign / NPCS_REL
    entries = scan(npcs)
    if not entries:
        print("nothing to classify")
        return None
    target = npcs / CLASSIFICATION_NAME
    previous: dict[str, dict] = {}
    if target.is_file():
        for e in _load_classification(target)["entries"]:
            if isinstance(e, dict) and "path" in e:
                previous[str(e["path"])] = e
    rows = []
    for p in entries:
        name = _entry_name(p)
        sha = _sha256_entry(p)
        git = _git_evidence(p)
        marker = _has_marker(p)
        disposition = _proposed(p)
        old = previous.get(name)
        if old and (old.get("evidence") or {}).get("sha256") == sha and old.get("disposition") in DISPOSITIONS:
            disposition = old["disposition"]
        row: dict[str, Any] = {"path": name, "disposition": disposition}
        if (disposition == "distilled" and isinstance(git, dict) and git["changed_since_added"]):
            row["flags"] = ["hand-edited"]
        row["evidence"] = {"source_extracts_marker": marker, "git": git, "sha256": sha, "size": _size(p)}
        rows.append(row)
    doc = {"campaign": campaign.name, "proposed_at_commit": _head(npcs), "entries": rows}
    atomic_write_text(target, yaml.safe_dump(doc, sort_keys=False, allow_unicode=True, width=1000))
    counts = {d: sum(1 for r in rows if r["disposition"] == d) for d in DISPOSITIONS}
    flagged = sum(1 for r in rows if r.get("flags"))
    print(f"Wrote {target}")
    print(f"{len(rows)} entries: {counts['distilled']} distilled, {counts['authored']} authored, "
          f"{counts['unknown']} unknown ({flagged} flagged hand-edited)")
    if counts["unknown"]:
        print("Set every `unknown` to `distilled` or `authored`, then run --apply.")
    return target


# ── config rewrites (line-level, comment-preserving, exact value only) ───────

_KEY_RE = re.compile(r"^(?P<indent> *)(?P<key>[A-Za-z_][\w-]*)\s*:(?P<rest>.*)$")
_VALUE_RE = re.compile(r"^(?P<ws>\s*)(?P<val>'[^']*'|\"[^\"]*\"|[^#\s][^#]*?)(?P<tail>\s*(?:#.*)?)$")
_ITEM_RE = re.compile(r"^(?P<prefix>\s*(?:-\s+)?)dossier\s*:(?P<rest>.*)$")


def _unquote(v: str) -> tuple[str, str]:
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
        return v[1:-1], v[0]
    return v, ""


def _split_value(rest: str):
    m = _VALUE_RE.match(rest.rstrip("\n").rstrip("\r"))
    if not m:
        return None
    raw, quote = _unquote(m.group("val"))
    return m.group("ws"), raw, quote, m.group("tail")


def rewrite_grounding(path: Path) -> tuple[bool, list[str]]:
    """``planning.dossiers.dossier_dir``: ``docs/npcs/`` -> ``docs/npcs/distilled/``."""
    if not path.is_file():
        return False, []
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    stack: list[tuple[int, str]] = []
    changed, notes = False, []
    for i, line in enumerate(lines):
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        m = _KEY_RE.match(line.rstrip("\r\n"))
        if not m:
            continue
        indent = len(m.group("indent"))
        while stack and stack[-1][0] >= indent:
            stack.pop()
        key = m.group("key")
        if key == "dossier_dir" and [k for _, k in stack] == ["planning", "dossiers"]:
            parts = _split_value(m.group("rest"))
            if parts:
                ws, raw, quote, tail = parts
                if raw == OLD_DOSSIER_DIR:
                    eol = line[len(line.rstrip("\r\n")):]
                    lines[i] = f"{m.group('indent')}dossier_dir:{ws}{quote}{NEW_DOSSIER_DIR}{quote}{tail}{eol}"
                    changed = True
                elif raw and raw != NEW_DOSSIER_DIR and raw.lower() != "null":
                    notes.append(f"{path.name}: planning.dossiers.dossier_dir is {raw!r}, not "
                                 f"{OLD_DOSSIER_DIR!r}; left unchanged")
        stack.append((indent, key))
    if changed:
        atomic_write_text(path, "".join(lines))
    return changed, notes


def rewrite_planning(path: Path, dispositions: dict[str, str]) -> tuple[int, list[str]]:
    """``npcs[].dossier`` values follow their file's disposition (``docs/npcs/x.md`` -> ``.../<disp>/x.md``)."""
    if not path.is_file():
        return 0, []
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    top = ""
    changed, notes = 0, []
    for i, line in enumerate(lines):
        if line.strip() and not line.startswith((" ", "\t", "#", "-")):
            km = _KEY_RE.match(line.rstrip("\r\n"))
            if km:
                top = km.group("key")
        if top != "npcs" or line.lstrip().startswith("#"):
            continue
        m = _ITEM_RE.match(line.rstrip("\r\n"))
        if not m:
            continue
        parts = _split_value(m.group("rest"))
        if not parts:
            continue
        ws, raw, quote, tail = parts
        rel = raw[len(OLD_DOSSIER_DIR):] if raw.startswith(OLD_DOSSIER_DIR) else None
        if rel is not None and "/" not in rel and dispositions.get(rel) in ("distilled", "authored"):
            eol = line[len(line.rstrip("\r\n")):]
            new = f"{OLD_DOSSIER_DIR}{dispositions[rel]}/{rel}"
            lines[i] = f"{m.group('prefix')}dossier:{ws}{quote}{new}{quote}{tail}{eol}"
            changed += 1
        elif not raw.startswith((f"{OLD_DOSSIER_DIR}{DISTILLED}/", f"{OLD_DOSSIER_DIR}{AUTHORED}/")):
            notes.append(f"{path.name}: dossier {raw!r} is not a classified docs/npcs/ file; left unchanged")
    if changed:
        atomic_write_text(path, "".join(lines))
    return changed, notes


# ── apply ────────────────────────────────────────────────────────────────────

def _validate(data: dict) -> list[dict]:
    rows = []
    for i, e in enumerate(data["entries"], 1):
        if not isinstance(e, dict) or not isinstance(e.get("path"), str) or not e["path"]:
            raise MigrationError(f"classification entry {i} has no `path`")
        if e.get("disposition") not in DISPOSITIONS:
            raise MigrationError(f"{e['path']}: disposition {e.get('disposition')!r} is not one of "
                                 f"{', '.join(DISPOSITIONS)}")
        sha = (e.get("evidence") or {}).get("sha256")
        if not isinstance(sha, str):
            raise MigrationError(f"{e['path']}: no evidence.sha256 to verify against; re-run --propose")
        rows.append(e)
    names = [r["path"] for r in rows]
    if len(set(names)) != len(names):
        raise MigrationError("duplicate paths in the classification file")
    return rows


def _external_report(provenance_path: Path | None) -> list[str]:
    out = []
    if provenance_path is not None and provenance_path.is_file():
        for n, line in enumerate(provenance_path.read_text(encoding="utf-8").splitlines(), 1):
            if "docs/npcs/" in line:
                out.append(f"  {provenance_path}:{n}: {line.strip()}")
    return out


def apply(campaign_dir: Path | str, *, force: bool = False,
          provenance_path: Path | str | None = "default") -> dict[str, Any]:
    """Follow the GM-edited classification. Returns ``{"moved": [...], "notes": [...]}``."""
    campaign = Path(campaign_dir).expanduser().resolve()
    npcs = campaign / NPCS_REL
    record = npcs / CLASSIFICATION_NAME
    on_disk = {_entry_name(p): p for p in scan(npcs)}
    moved: list[str] = []

    if not record.is_file():
        if on_disk:
            raise MigrationError(
                f"{record} does not exist but docs/npcs/ holds {len(on_disk)} unclassified entr"
                f"{'y' if len(on_disk) == 1 else 'ies'}; run --propose first")
        rows: list[dict] = []   # nothing to move: config-only campaign
    else:
        rows = _validate(_load_classification(record))
        unknown = sorted(r["path"] for r in rows if r["disposition"] == "unknown")
        if unknown:
            raise MigrationError(
                f"{len(unknown)} entr{'y is' if len(unknown) == 1 else 'ies are'} still `unknown` "
                f"(nothing moved): {', '.join(unknown[:10])}{' ...' if len(unknown) > 10 else ''}. "
                f"Set each to `distilled` or `authored` in {record}")

    by_name = {r["path"]: r for r in rows}
    # The disk must match the proposal: nothing added, removed or edited since.
    problems = []
    for name, p in sorted(on_disk.items()):
        if name not in by_name:
            problems.append(f"{name}: added since --propose")
        elif _sha256_entry(p) != by_name[name]["evidence"]["sha256"]:
            problems.append(f"{name}: changed since --propose")
    plan: list[tuple[str, Path, Path]] = []
    for name, r in sorted(by_name.items()):
        target = npcs / r["disposition"] / name.rstrip("/")
        if name in on_disk:
            plan.append((name, on_disk[name], target))
        elif target.exists() and _sha256_entry(target) == r["evidence"]["sha256"]:
            continue   # already moved (resumed or repeated run)
        else:
            problems.append(f"{name}: removed since --propose")
    if problems:
        raise MigrationError("the disk no longer matches the proposal (nothing moved):\n  "
                             + "\n  ".join(problems) + "\nRe-run --propose.")
    clashes = []
    for name, _src, target in plan:
        if target.exists():
            if target.is_dir() or _src.is_dir():
                clashes.append(f"{target.relative_to(campaign)} (a directory cannot be replaced; move it away)")
            elif not force:
                clashes.append(str(target.relative_to(campaign)))
    if clashes:
        raise MigrationError("target(s) already exist (nothing moved; --force replaces files):\n  "
                             + "\n  ".join(clashes))

    for name, src, target in plan:
        try:
            target.parent.mkdir(parents=True, exist_ok=True)
            os.replace(src, target)
        except OSError as exc:
            done = ", ".join(moved) or "(none)"
            raise MigrationError(f"moving {name} failed ({exc}); moved so far: {done}. "
                                 f"Fix the cause and re-run --apply to resume.") from exc
        moved.append(name)

    dispositions = {n.rstrip("/"): r["disposition"] for n, r in by_name.items()}
    notes: list[str] = []
    changed_g, n1 = rewrite_grounding(config_path(campaign, "grounding.yaml"))
    n_plan, n2 = rewrite_planning(config_path(campaign, "planning.yaml"), dispositions)
    notes += n1 + n2

    print(f"Moved {len(moved)} entr{'y' if len(moved) == 1 else 'ies'} "
          f"({sum(1 for n in moved if by_name[n]['disposition'] == 'distilled')} to {DISTILLED}/, "
          f"{sum(1 for n in moved if by_name[n]['disposition'] == 'authored')} to {AUTHORED}/).")
    print(f"grounding.yaml dossier_dir rewritten: {'yes' if changed_g else 'no'}; "
          f"planning.yaml dossier paths rewritten: {n_plan}")
    for line in notes:
        print(f"  not changed: {line}")
    prov = (Path.home() / "src" / "campaigns" / "provenance.yaml") if provenance_path == "default" \
        else (Path(provenance_path) if provenance_path else None)
    hits = _external_report(prov)
    print("External references this migration does not edit:")
    for line in hits:
        print(line)
    for line in EXTERNAL_NOTES:
        print(f"  - {line}")
    print(CLOSING)
    return {"moved": moved, "notes": notes}


# ── CLI ──────────────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0], prog="migrate_npc_dossiers")
    parser.add_argument("--campaign-dir", required=True, metavar="DIR")
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--propose", action="store_true",
                      help=f"write docs/npcs/{CLASSIFICATION_NAME} (moves nothing)")
    mode.add_argument("--apply", action="store_true", help="follow the GM-edited classification file")
    parser.add_argument("--force", action="store_true",
                        help="with --apply: replace same-named files already in distilled/ or authored/")
    args = parser.parse_args(argv)
    if args.force and not args.apply:
        parser.error("--force only applies with --apply")
    campaign = Path(args.campaign_dir).expanduser()
    if not campaign.is_dir():
        print(f"Error: not a directory: {campaign}", file=sys.stderr)
        return 1
    try:
        if args.propose:
            propose(campaign)
        else:
            apply(campaign, force=args.force)
    except MigrationError as exc:
        print(f"Error: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
