#!/usr/bin/env python3
"""Generate a SHORT-TERM world-state document (recent_events.md).

The ensemble pipeline produces a LONG-TERM world state (`synthesise_world_state.py`
over per-entity dossiers with a fact-count / known-only filter): only entities that
*persist* across chapters survive, so a one-session goblin boss correctly ages out.
That is the "what is true across the whole campaign" view.

This tool produces its short-term companion: a MECHANICAL, full-fidelity,
chapter-ordered render of every in-world `event` fact in a recent window. There is
no synthesis step — synthesis is exactly what drops low-persistence facts, so the
short-term record must bypass it. This is the "what happened in chapter N" view,
where a one-session combatant IS material.

Fact-count is a proxy for persistence, and the right threshold scales with the query
window: window = whole campaign -> high threshold (long-term world_state); window = a
few recent chapters -> threshold ~0 (this file). As chapters pass, slide --window
forward so the short-term record stays bounded; anything that mattered long-term has
already been captured by world_state synthesis.

Run from inside a campaign dir, consistent with the other CampaignGenerator tools:

  build_recent_events \
      --corpus 'docs/ensemble/per_chapter/*/merged.json' \
      --output docs/recent_events.md \
      --window 0            # 0 = all chapters; N = keep only the last N
"""
import argparse
import glob
import json
import re
from collections import defaultdict
from pathlib import Path

# table/OOC chatter, not in-world events (VTT/Zoom recaps capture table talk)
OOC = re.compile(
    r"discord|spreadsheet|action economy|rpgbot|reference guide|audio|"
    r"claude-based|name generator|next session|pinned|initiative of|"
    r"rolled (a |an )?\d|roll(ed)? (of |totaled )|disadvantage|advantage on|"
    r"armor class of|saving throw mechanic",
    re.I,
)

# chapter index from the per-chapter dir/file name (chapter_02_*, session_001_*, ch3, gen-ch5, ...)
CHAP = re.compile(r"(?:chapter|session|ch|gen-ch)[_-]?0*(\d+)", re.I)


def chapter_of(path: str) -> int:
    # prefer an explicit chapter/session token; fall back to the last number in the path
    for seg in reversed(Path(path).parts):
        m = CHAP.search(seg)
        if m:
            return int(m.group(1))
    nums = re.findall(r"\d+", path)
    return int(nums[-1]) if nums else 99


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", required=True, nargs="+", metavar="GLOB",
                    help="merged.json glob(s), e.g. 'docs/ensemble/per_chapter/*/merged.json'")
    ap.add_argument("--output", "-o", default="docs/recent_events.md", type=Path,
                    help="Output markdown (default: docs/recent_events.md)")
    ap.add_argument("--window", type=int, default=0,
                    help="Keep only the last N chapters (0 = all)")
    ap.add_argument("--campaign", default=None,
                    help="Campaign label for the header (default: current dir name)")
    args = ap.parse_args()

    files = sorted({f for g in args.corpus for f in glob.glob(g)})
    if not files:
        ap.error(f"no files matched: {args.corpus}")

    by_chap = defaultdict(list)
    seen = set()
    for f in files:
        ch = chapter_of(f)
        for fa in json.load(open(f, encoding="utf-8")):
            if fa.get("type") != "event":
                continue
            text = (fa.get("fact") or "").strip()
            if not text or OOC.search(text):
                continue
            key = re.sub(r"[^a-z0-9 ]", "", text.lower())[:60]
            if key in seen:
                continue
            seen.add(key)
            by_chap[ch].append(text)

    chapters = sorted(by_chap)
    if args.window and len(chapters) > args.window:
        chapters = chapters[-args.window:]

    campaign = args.campaign or Path.cwd().name
    window_line = (
        f"_Window: {'all chapters' if not args.window else f'last {args.window} chapters'} "
        f"(chapters {chapters[0]}–{chapters[-1]})._" if chapters else "_No events._"
    )
    lines = [
        f"# Recent Events — {campaign} (short-term world state)",
        "",
        "_Mechanically generated by `build_recent_events.py` — full-fidelity, chapter-ordered,",
        "**not** synthesised (synthesis drops low-persistence facts). Every in-world event in",
        "the window is kept, down to one-session combatants. The long-term, persistence-filtered",
        "view is `docs/world_state.md`; this is the \"what happened in chapter N\" companion.",
        "Regenerate after each session; slide `--window` forward as the campaign grows._",
        "",
        window_line,
        "",
    ]
    for c in chapters:
        lines.append(f"## Chapter {c}" if c != 99 else "## Unanchored")
        lines.append("")
        lines.extend(f"- {t}" for t in by_chap[c])
        lines.append("")

    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    kept = sum(len(by_chap[c]) for c in chapters)
    print(f"wrote {args.output}: {kept} events across {len(chapters)} chapter(s) "
          f"(window={args.window or 'all'})")


if __name__ == "__main__":
    main()
