#!/usr/bin/env python3
"""Create a new CampaignGenerator workspace directory.

Sets up the standard campaign layout expected by both the CLI tools and the
FastAPI + Vue web UI:

    <workspace>/
        config.yaml         ← shared config (portable: relative paths)
        docs/               ← campaign_state.md, world_state.md, party.md, ...
        voice/              ← per-character voice files
        examples/           ← handcrafted style references
        summaries/          ← per-session directories
        logs/               ← auto-generated session logs

If you already have files, point to them with --world-state, --mechanics,
--planning, etc. The config will reference them directly (no copying).
If omitted, placeholder files are created inside the workspace.

Usage:
  new_workspace ~/campaigns/icespire
  new_workspace ~/campaigns/icespire --name "Icespire Peak"
  new_workspace ~/campaigns/icespire \\
      --world-state ~/Phandalin/neverwinter_lore.md \\
      --mechanics   ~/Phandalin/arc_scores.md \\
      --planning    ~/Phandalin/enemy_dossiers.md
"""

import argparse
import sys
from pathlib import Path

# This file lives at pipelines/workspace/new_workspace.py; the "next steps"
# commands printed below reference sibling scripts and `startup` that still
# live at the repo root, so resolve the repo root explicitly rather than
# assuming they're this file's own siblings.
REPO_ROOT = Path(__file__).resolve().parent.parent.parent

CONFIG_TEMPLATE = """\
# CampaignGenerator workspace config
# Generated by new_workspace.py — edit paths here if you move files.

system_prompt: {system_prompt}

log_dir: {log_dir}

# Agent prompts for --mode pipeline (kept in the code directory)
agents:
  lore_oracle: {lore_oracle}
  encounter_architect: {encounter_architect}
  voice_keeper: {voice_keeper}

documents:
  - label: campaign_state
    path: {campaign_state}
  - label: world_state
    path: {world_state}
  - label: mechanics
    path: {mechanics}
  - label: planning
    path: {planning}
  - label: party
    path: {party}
"""

CAMPAIGN_STATE_TEMPLATE = """\
# Campaign State — {name}

_Generated by campaign_state.py from session summaries. Re-run to update after each session._
_This document grounds all session prep: it tells the AI what is DONE and what is CURRENTLY TRUE._

## Completed Encounters & Quests

_None yet — run `python campaign_state.py summaries.md --output docs/campaign_state.md`_

## Resolved Plot Threads

## NPC Current States

| NPC | Status | Last Known Location | Disposition toward Party |
|---|---|---|---|

## Active Quests & Open Threads

## Party Current Situation

- **Current location:**
- **Active obligations:**
"""

WORLD_STATE_TEMPLATE = """\
# World State — {name}

_Paste or write your living canon document here._
_This is the source of truth for all session prep._
"""

MECHANICS_TEMPLATE = """\
# Mechanics — {name}

_Arc score systems, house rules, and mechanical notes go here._
"""

PLANNING_TEMPLATE = """\
# Planning — {name}

_Enemy dossiers, NPC notes, and forward-planning documents go here._
"""

PARTY_TEMPLATE = """\
# Party — {name}

_Current party roster. Keep this up to date after each session._

## Characters

| Name | Class / Level | Player | Arc Score Track |
|---|---|---|---|
| | | | |

## Arc Scores

_Define each arc score track, its current value, and trigger conditions._

## Party State

_Current location, active quests, key items held, and outstanding obligations._
"""


def resolve_existing(flag: str, value: str) -> Path:
    p = Path(value).expanduser().resolve()
    if not p.exists():
        print(f"Error: {flag} file not found: {p}", file=sys.stderr)
        sys.exit(1)
    return p


def placeholder(docs_dir: Path, filename: str, content: str) -> Path:
    p = docs_dir / filename
    p.write_text(content, encoding="utf-8")
    return p


def rel_to_workspace(path: Path, workspace: Path) -> str:
    """Express ``path`` relative to ``workspace`` when it lives inside it.

    Keeps generated configs portable: campaign-local docs/logs become
    ``docs/world_state.md`` / ``logs`` (resolved against the config's own
    directory at load time), so the checked-in config survives a different
    username or clone location. Paths outside the workspace stay absolute.
    """
    try:
        return str(path.relative_to(workspace))
    except ValueError:
        return str(path)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a new CampaignGenerator workspace."
    )
    parser.add_argument(
        "path",
        help="Directory to create the workspace in (e.g. ~/campaigns/icespire)",
    )
    parser.add_argument(
        "--name", "-n",
        default=None,
        help="Campaign name, used in placeholder file headers (default: directory name)",
    )
    parser.add_argument(
        "--world-state",
        metavar="FILE",
        help="Existing world-state / lore file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--mechanics",
        metavar="FILE",
        help="Existing mechanics file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--planning",
        metavar="FILE",
        help="Existing planning file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--party",
        metavar="FILE",
        help="Existing party file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--campaign-state",
        metavar="FILE",
        help="Existing campaign state file to use instead of creating a placeholder",
    )
    args = parser.parse_args()

    workspace = Path(args.path).expanduser().resolve()
    name = args.name or workspace.name

    if workspace.exists() and any(workspace.iterdir()):
        print(f"Error: '{workspace}' already exists and is not empty.", file=sys.stderr)
        sys.exit(1)

    docs_dir = workspace / "docs"
    logs_dir = workspace / "logs"
    voice_dir = workspace / "voice"
    examples_dir = workspace / "examples"
    summaries_dir = workspace / "summaries"
    for d in (docs_dir, logs_dir, voice_dir, examples_dir, summaries_dir):
        d.mkdir(parents=True, exist_ok=True)

    # Resolve each doc: use supplied path or create a placeholder
    if args.campaign_state:
        campaign_state_path = resolve_existing("--campaign-state", args.campaign_state)
        campaign_state_note = f"← {campaign_state_path}"
    else:
        campaign_state_path = placeholder(docs_dir, "campaign_state.md",
                                          CAMPAIGN_STATE_TEMPLATE.format(name=name))
        campaign_state_note = "← run campaign_state.py to populate"

    if args.world_state:
        world_state_path = resolve_existing("--world-state", args.world_state)
        world_state_note = f"← {world_state_path}"
    else:
        world_state_path = placeholder(docs_dir, "world_state.md",
                                       WORLD_STATE_TEMPLATE.format(name=name))
        world_state_note = "← paste your lore here"

    if args.mechanics:
        mechanics_path = resolve_existing("--mechanics", args.mechanics)
        mechanics_note = f"← {mechanics_path}"
    else:
        mechanics_path = placeholder(docs_dir, "mechanics.md",
                                     MECHANICS_TEMPLATE.format(name=name))
        mechanics_note = "← arc scores, house rules"

    if args.planning:
        planning_path = resolve_existing("--planning", args.planning)
        planning_note = f"← {planning_path}"
    else:
        planning_path = placeholder(docs_dir, "planning.md",
                                    PLANNING_TEMPLATE.format(name=name))
        planning_note = "← enemy dossiers, NPC notes"

    if args.party:
        party_path = resolve_existing("--party", args.party)
        party_note = f"← {party_path}"
    else:
        party_path = placeholder(docs_dir, "party.md",
                                 PARTY_TEMPLATE.format(name=name))
        party_note = "← current party roster and arc scores"

    # Write config.yaml (CLI tools)
    config_content = CONFIG_TEMPLATE.format(
        # Code-repo prompts: relative names, auto-discovered against the
        # CampaignGenerator checkout by load_repo_file — no machine-specific path.
        system_prompt="config/system_prompt.md",
        log_dir=rel_to_workspace(logs_dir, workspace),
        lore_oracle="config/agents/lore_oracle.md",
        encounter_architect="config/agents/encounter_architect.md",
        voice_keeper="config/agents/voice_keeper.md",
        # Campaign docs: relative to the workspace so the config stays portable.
        campaign_state=rel_to_workspace(campaign_state_path, workspace),
        world_state=rel_to_workspace(world_state_path, workspace),
        mechanics=rel_to_workspace(mechanics_path, workspace),
        planning=rel_to_workspace(planning_path, workspace),
        party=rel_to_workspace(party_path, workspace),
    )
    config_path = workspace / "config.yaml"
    config_path.write_text(config_content, encoding="utf-8")

    # Summary
    print(f"\nWorkspace created: {workspace}")
    print(f"\n  {workspace}/")
    print(f"  ├── config.yaml          ← CLI + Web UI config")
    print(f"  ├── docs/")
    doc_items = [
        (args.campaign_state, "campaign_state.md", campaign_state_path, campaign_state_note),
        (args.world_state, "world_state.md", world_state_path, world_state_note),
        (args.mechanics, "mechanics.md", mechanics_path, mechanics_note),
        (args.planning, "planning.md", planning_path, planning_note),
        (args.party, "party.md", party_path, party_note),
    ]
    for i, (is_external, filename, path, note) in enumerate(doc_items):
        connector = "└" if i == len(doc_items) - 1 else "├"
        if is_external:
            print(f"  │   {connector}── {filename:<20s} → {path}")
        else:
            print(f"  │   {connector}── {filename:<20s} {note}")
    print(f"  ├── voice/               ← per-character voice files")
    print(f"  ├── examples/            ← handcrafted style references")
    print(f"  ├── summaries/           ← per-session directories")
    print(f"  └── logs/                ← auto-generated session logs")
    print(f"\nNext steps:")
    print(f"  1. Generate campaign_state.md from your session summaries:")
    print(f"     python {REPO_ROOT}/campaign_state.py summaries.md --output {docs_dir}/campaign_state.md")
    if not (args.world_state and args.mechanics and args.planning):
        print(f"  2. Fill in any other placeholder docs/ files with your campaign content")
    print(f"  3. Run prep from anywhere:")
    print(f"     prep --config {config_path} --beat \"...\"")
    print(f"  4. Or launch the web UI:")
    print(f"     cd {workspace} && {REPO_ROOT}/startup")
    print()


if __name__ == "__main__":
    main()
