#!/usr/bin/env python3
"""Create a new CampaignGenerator workspace directory.

Sets up the standard campaign layout expected by both the CLI tools and the
FastAPI + Vue web UI:

    <workspace>/
        config/config.yaml  ← shared config (portable: paths relative to config/)
        docs/               ← campaign_state.md, world_state.md, party.md, ...
        voice/              ← per-character voice files
        examples/           ← handcrafted style references
        summaries/          ← per-session directories
        logs/               ← auto-generated session logs

If you already have files, point to them with --world-state, --mechanics,
--planning, etc. The config will reference them directly (no copying).
If omitted, placeholder files are created inside the workspace.

Usage:
  new_workspace ~/campaigns/icespire
  new_workspace ~/campaigns/icespire --name "Icespire Peak"
  new_workspace ~/campaigns/icespire \\
      --world-state ~/Phandalin/neverwinter_lore.md \\
      --mechanics   ~/Phandalin/arc_scores.md \\
      --planning    ~/Phandalin/enemy_dossiers.md
"""

import argparse
import os
import sys
from pathlib import Path

from campaignlib.constants import CONFIG_DIR_NAME

CONFIG_TEMPLATE = """\
# CampaignGenerator workspace config
# Generated by new_workspace.py — edit paths here if you move files.

system_prompt: {system_prompt}

log_dir: {log_dir}

# Agent prompts for --mode pipeline (campaign overrides or shipped defaults)
agents:
  lore_oracle: {lore_oracle}
  encounter_architect: {encounter_architect}
  voice_keeper: {voice_keeper}

documents:
  - label: campaign_state
    path: {campaign_state}
  - label: world_state
    path: {world_state}
  - label: mechanics
    path: {mechanics}
  - label: planning
    path: {planning}
  - label: party
    path: {party}
"""

CAMPAIGN_STATE_TEMPLATE = """\
# Campaign State — {name}

_Generated by the `campaign_state` command from session summaries. Re-run to update after each session._
_This document grounds all session prep: it tells the AI what is DONE and what is CURRENTLY TRUE._

## Completed Encounters & Quests

_None yet — run `campaign_state summaries.md --output docs/campaign_state.md`_

## Resolved Plot Threads

## NPC Current States

| NPC | Status | Last Known Location | Disposition toward Party |
|---|---|---|---|

## Active Quests & Open Threads

## Party Current Situation

- **Current location:**
- **Active obligations:**

## Audit: Tracking Claims

_No tracking claims have been audited yet._
"""

WORLD_STATE_TEMPLATE = """\
# World State — {name}

## Party
_Add established party facts._
## Factions and Powers
_Add factions and powers._
## Key NPCs
_Add key NPCs._
## Locations
_Add established locations._
## Items and Artifacts
_Add important items._
## Active Threats and Open Pressures
_Add active pressures._
## Canon Events Timeline
_Add canonical events._
"""

MECHANICS_TEMPLATE = """\
# Mechanics — {name}

_Arc score systems, house rules, and mechanical notes go here._
"""

PLANNING_TEMPLATE = """\
# Planning — {name}

## Threat Tracker
_Add current threats._
## NPC Dossiers
_Add NPC plans._
## Faction States
_Add faction plans._
## Active Plots
_Add active plots._
## DM Notes
_Add private planning notes._
"""

PARTY_TEMPLATE = """\
# Party — {name}

## Party Overview
_Add the party's current situation._

## Characters
| Name | Class / Level | Player | Arc Score Track |
|---|---|---|---|
| | | | |

## Party Dynamics
_Add resources, relationships, and character arc tracking._
"""


def resolve_existing(flag: str, value: str) -> Path:
    p = Path(value).expanduser().resolve()
    if not p.exists():
        print(f"Error: {flag} file not found: {p}", file=sys.stderr)
        sys.exit(1)
    return p


def placeholder(docs_dir: Path, filename: str, content: str) -> Path:
    p = docs_dir / filename
    p.write_text(content, encoding="utf-8")
    return p


def rel_to_workspace(path: Path, workspace: Path) -> str:
    """Express ``path`` relative to ``workspace`` when it lives inside it.

    For ``log_dir``, which is not resolved against the config's directory.
    Paths outside the workspace stay absolute.
    """
    try:
        return str(path.relative_to(workspace))
    except ValueError:
        return str(path)


def rel_to_config(path: Path, workspace: Path, config_dir: Path) -> str:
    """Express a document ``path`` relative to ``config_dir`` when it lives
    inside the workspace.

    ``load_config`` resolves ``documents[].path`` against the config file's
    own directory, which is ``<workspace>/config/``, so a campaign-local doc
    becomes ``../docs/world_state.md``. Keeps the checked-in config portable
    across usernames and clone locations. Paths outside the workspace stay
    absolute.
    """
    try:
        path.relative_to(workspace)
    except ValueError:
        return str(path)
    return os.path.relpath(path, config_dir)


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Create a new CampaignGenerator workspace."
    )
    parser.add_argument(
        "path",
        help="Directory to create the workspace in (e.g. ~/campaigns/icespire)",
    )
    parser.add_argument(
        "--name", "-n",
        default=None,
        help="Campaign name, used in placeholder file headers (default: directory name)",
    )
    parser.add_argument(
        "--world-state",
        metavar="FILE",
        help="Existing world-state / lore file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--mechanics",
        metavar="FILE",
        help="Existing mechanics file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--planning",
        metavar="FILE",
        help="Existing planning file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--party",
        metavar="FILE",
        help="Existing party file to use instead of creating a placeholder",
    )
    parser.add_argument(
        "--campaign-state",
        metavar="FILE",
        help="Existing campaign state file to use instead of creating a placeholder",
    )
    args = parser.parse_args()

    workspace = Path(args.path).expanduser().resolve()
    name = args.name or workspace.name

    if workspace.exists() and any(workspace.iterdir()):
        print(f"Error: '{workspace}' already exists and is not empty.", file=sys.stderr)
        sys.exit(1)

    config_dir = workspace / CONFIG_DIR_NAME
    docs_dir = workspace / "docs"
    logs_dir = workspace / "logs"
    voice_dir = workspace / "voice"
    examples_dir = workspace / "examples"
    summaries_dir = workspace / "summaries"
    for d in (config_dir, docs_dir, logs_dir, voice_dir, examples_dir, summaries_dir):
        d.mkdir(parents=True, exist_ok=True)

    # Resolve each doc: use supplied path or create a placeholder
    if args.campaign_state:
        campaign_state_path = resolve_existing("--campaign-state", args.campaign_state)
        campaign_state_note = f"← {campaign_state_path}"
    else:
        campaign_state_path = placeholder(docs_dir, "campaign_state.md",
                                          CAMPAIGN_STATE_TEMPLATE.format(name=name))
        campaign_state_note = "← run campaign_state to populate"

    if args.world_state:
        world_state_path = resolve_existing("--world-state", args.world_state)
        world_state_note = f"← {world_state_path}"
    else:
        world_state_path = placeholder(docs_dir, "world_state.md",
                                       WORLD_STATE_TEMPLATE.format(name=name))
        world_state_note = "← paste your lore here"

    if args.mechanics:
        mechanics_path = resolve_existing("--mechanics", args.mechanics)
        mechanics_note = f"← {mechanics_path}"
    else:
        mechanics_path = placeholder(docs_dir, "mechanics.md",
                                     MECHANICS_TEMPLATE.format(name=name))
        mechanics_note = "← arc scores, house rules"

    if args.planning:
        planning_path = resolve_existing("--planning", args.planning)
        planning_note = f"← {planning_path}"
    else:
        planning_path = placeholder(docs_dir, "planning.md",
                                    PLANNING_TEMPLATE.format(name=name))
        planning_note = "← enemy dossiers, NPC notes"

    if args.party:
        party_path = resolve_existing("--party", args.party)
        party_note = f"← {party_path}"
    else:
        party_path = placeholder(docs_dir, "party.md",
                                 PARTY_TEMPLATE.format(name=name))
        party_note = "← current party roster and arc scores"

    # New workspaces explicitly remain migration-required. They do not
    # silently present loose files as an active managed generation. External
    # document arguments remain references and are never copied into members.
    placeholder(
        docs_dir,
        "canon_events_timeline.md",
        f"# Canon Events Timeline — {name}\n\n_No canonical events recorded yet._\n",
    )
    (docs_dir / "reference").mkdir(exist_ok=True)
    (docs_dir / "grounding-migration-required.md").write_text(
        "# Grounding bundle migration required\n\n"
        "Run `migrate_grounding_bundle plan --campaign-dir .`, review the plan, "
        "then apply it before using managed grounding readers or writers.\n",
        encoding="utf-8",
    )

    # Write config.yaml (CLI tools)
    config_content = CONFIG_TEMPLATE.format(
        # Logical prompt names: campaign overrides win, then packaged defaults.
        system_prompt="config/system_prompt.md",
        log_dir=rel_to_workspace(logs_dir, workspace),
        lore_oracle="config/agents/lore_oracle.md",
        encounter_architect="config/agents/encounter_architect.md",
        voice_keeper="config/agents/voice_keeper.md",
        # Campaign docs: relative to the workspace so the config stays portable.
        campaign_state=rel_to_config(campaign_state_path, workspace, config_dir),
        world_state=rel_to_config(world_state_path, workspace, config_dir),
        mechanics=rel_to_config(mechanics_path, workspace, config_dir),
        planning=rel_to_config(planning_path, workspace, config_dir),
        party=rel_to_config(party_path, workspace, config_dir),
    )
    config_path = config_dir / "config.yaml"
    config_path.write_text(config_content, encoding="utf-8")

    # Summary
    print(f"\nWorkspace created: {workspace}")
    print(f"\n  {workspace}/")
    print(f"  ├── {CONFIG_DIR_NAME}/config.yaml   ← CLI + Web UI config")
    print(f"  ├── docs/")
    doc_items = [
        (args.campaign_state, "campaign_state.md", campaign_state_path, campaign_state_note),
        (args.world_state, "world_state.md", world_state_path, world_state_note),
        (args.mechanics, "mechanics.md", mechanics_path, mechanics_note),
        (args.planning, "planning.md", planning_path, planning_note),
        (args.party, "party.md", party_path, party_note),
    ]
    for i, (is_external, filename, path, note) in enumerate(doc_items):
        connector = "└" if i == len(doc_items) - 1 else "├"
        if is_external:
            print(f"  │   {connector}── {filename:<20s} → {path}")
        else:
            print(f"  │   {connector}── {filename:<20s} {note}")
    print(f"  ├── voice/               ← per-character voice files")
    print(f"  ├── examples/            ← handcrafted style references")
    print(f"  ├── summaries/           ← per-session directories")
    print(f"  └── logs/                ← auto-generated session logs")
    print(f"\nNext steps:")
    print(f"  1. Generate campaign_state.md from your session summaries:")
    print(f"     campaign_state summaries.md --output {docs_dir}/campaign_state.md")
    if not (args.world_state and args.mechanics and args.planning):
        print(f"  2. Fill in any other placeholder docs/ files with your campaign content")
    print(f"  3. Run prep from anywhere:")
    print(f"     prep --config {config_path} --beat \"...\"")
    print(f"  4. Or launch the web UI from a source checkout (checkout-only):")
    print(f"     cd <CampaignGenerator checkout> && ./start --campaign-dir {workspace}")
    print()


if __name__ == "__main__":
    main()
