"""Deterministic citation verification for distill.py's extract and
synthesize passes.

distill_extract.md requires every extracted bullet to end with a citation
tag — `[cite: "..."]` — quoting the source text it was drawn from. This
module checks that requirement mechanically: no model call, just a
substring match between the cited quote and the chunk it claims to come
from. A quote that doesn't match is a candidate hallucination, surfaced
for the GM to review at the existing --extract-only checkpoint rather than
silently trusted or silently discarded.

distill_synthesize.md carries the same discipline into the merge pass, but
as endnotes: every claim ends with `[n]`, and a `## Citations` section at
the end of the document maps each `n` to a quote copied verbatim from one
of the extraction notes' own `[cite: "..."]` tags. Because synthesis is
required to copy a citation forward rather than invent one, verifying an
endnote is a cheap exact-membership check against the set of citations the
extract pass already produced — no fuzzy source matching needed.
"""

import re
from dataclasses import dataclass

_QUOTE_OPEN = '«"“'
_QUOTE_CLOSE = '»"”'

_CITE_RE = re.compile(
    rf'^(?P<bullet>-\s.*?)\s*\[cite:\s*[{_QUOTE_OPEN}](?P<quote>.*?)[{_QUOTE_CLOSE}]\]\s*$',
    re.MULTILINE,
)
_CITE_TAG_RE = re.compile(rf'\[cite:\s*[{_QUOTE_OPEN}].*?[{_QUOTE_CLOSE}]\]\s*$')

_WHITESPACE_RE = re.compile(r'\s+')

# Models routinely re-encode a source's nested double quotes as single quotes
# to avoid colliding with the [cite: "..."] wrapper's own delimiters (e.g.
# source `named the party "the Obsidian Edge"` cited as `'the Obsidian Edge'`).
# That's a faithful quote, not a fabrication, so all quote styles collapse to
# one canonical mark before comparison — a genuinely different quote still
# fails on the words themselves.
_QUOTE_TRANSLATION = str.maketrans({c: "'" for c in '"“”‘’`'})


def _normalize(s: str) -> str:
    """Collapse whitespace/quote-style/case drift so only real wording
    differences count as a mismatch."""
    s = s.translate(_QUOTE_TRANSLATION)
    return _WHITESPACE_RE.sub(' ', s).strip().casefold()


@dataclass
class Citation:
    bullet: str
    quote: str
    verified: bool


def extract_citations(text: str) -> list[tuple[str, str]]:
    """Return (bullet, quote) for every cited bullet in an extract file."""
    return [
        (m.group('bullet').strip(), m.group('quote'))
        for m in _CITE_RE.finditer(text)
    ]


_EXEMPT_LABEL_RE = re.compile(
    r'^-\s*(Faction|Current location|Current goals):', re.IGNORECASE
)
_ABSENCE_RE = re.compile(
    r'^-\s*(does not appear|not (directly )?encountered|not (directly )?present|not visited)\b'
    r'[^.;]*\b(this (chunk|session|chapter))\b\.?$',
    re.IGNORECASE,
)


def _is_exempt_from_citation(stripped_line: str) -> bool:
    """`Faction:`/`Current location:`/`Current goals:` sub-fields classify
    rather than assert, and a bare not-in-this-chunk/session negative has
    nothing to quote by definition — both are allowed to skip the citation
    per distill_extract.md's exception rule."""
    return bool(_EXEMPT_LABEL_RE.match(stripped_line) or _ABSENCE_RE.match(stripped_line))


def find_uncited_bullets(text: str) -> list[str]:
    """Return bullet lines that carry no `[cite: ...]` tag and aren't exempt."""
    uncited = []
    for line in text.splitlines():
        stripped = line.strip()
        if (stripped.startswith('- ')
                and not _CITE_TAG_RE.search(stripped)
                and not _is_exempt_from_citation(stripped)):
            uncited.append(stripped)
    return uncited


def verify_citations(text: str, source: str) -> list[Citation]:
    """Check every cited quote in `text` is a verbatim substring of `source`.

    A citation is "verified" iff its quote (after whitespace/case
    normalization) appears somewhere in `source`. An empty quote never
    verifies.
    """
    norm_source = _normalize(source)
    return [
        Citation(bullet=bullet, quote=quote, verified=bool(quote) and _normalize(quote) in norm_source)
        for bullet, quote in extract_citations(text)
    ]


def render_report(results_by_file: dict[str, tuple[list[Citation], list[str]]]) -> str:
    """Render a citation_report.md body from {filename: (citations, uncited_bullets)}.

    Only files with at least one flagged item (unverified citation or
    uncited bullet) are included — a clean file has nothing to review.
    """
    lines = [
        "# Citation Report",
        "",
        "Generated by distill.py's citation check (plain substring matching,"
        " not a model call). Every bullet in extract_*.md is expected to end"
        " with `[cite: \"...\"]`, a verbatim quote from its source chunk."
        " Items below failed that check and are candidate hallucinations —"
        " verify against the source before this material reaches synthesis.",
    ]
    any_flagged = False
    for filename, (citations, uncited) in results_by_file.items():
        unverified = [c for c in citations if not c.verified]
        if not unverified and not uncited:
            continue
        any_flagged = True
        lines += ["", f"## {filename}"]
        if unverified:
            lines += ["", "### Unverified citations (quote not found in source)"]
            for c in unverified:
                lines.append(f'- {c.bullet}\n  cited: "{c.quote}"')
        if uncited:
            lines += ["", "### Bullets missing a citation"]
            for bullet in uncited:
                lines.append(f"- {bullet}")
    if not any_flagged:
        lines += ["", "No flagged claims — every bullet carried a citation that matched its source."]
    return "\n".join(lines) + "\n"


# ── Synthesis endnotes ───────────────────────────────────────────────────────

_ENDNOTE_DEF_RE = re.compile(
    rf'^\[(?P<num>\d+)\]\s*[{_QUOTE_OPEN}](?P<quote>.*?)[{_QUOTE_CLOSE}]\s*$',
    re.MULTILINE,
)
_TRAILING_ENDNOTE_REFS_RE = re.compile(r'((?:\[\d+\])+)\s*$')
_CITATIONS_HEADING_RE = re.compile(r'^##\s*Citations\s*$', re.IGNORECASE | re.MULTILINE)


@dataclass
class Endnote:
    number: int
    quote: str
    verified: bool


def _split_body_and_citations(text: str) -> tuple[str, str]:
    """Split a synthesized document into (body, citations_section).

    If no `## Citations` heading is found, the whole document is treated as
    body and the citations section is empty — every claim will then
    correctly show up as unreferenced rather than silently skipped.
    """
    m = _CITATIONS_HEADING_RE.search(text)
    if not m:
        return text, ''
    return text[:m.start()], text[m.end():]


def extract_endnote_definitions(text: str) -> dict[int, str]:
    """Parse the `## Citations` section into {number: quote}."""
    _, citations_text = _split_body_and_citations(text)
    return {int(m.group('num')): m.group('quote') for m in _ENDNOTE_DEF_RE.finditer(citations_text)}


def find_endnote_refs(text: str) -> list[tuple[str, list[int]]]:
    """Return (claim, [endnote numbers]) for every body claim ending in a
    trailing run of `[n]` markers, e.g. `...before the coup. [2][5]`."""
    body, _ = _split_body_and_citations(text)
    refs = []
    for line in body.splitlines():
        stripped = line.strip()
        if not stripped.startswith('- '):
            continue
        m = _TRAILING_ENDNOTE_REFS_RE.search(stripped)
        if m:
            nums = [int(n) for n in re.findall(r'\d+', m.group(1))]
            refs.append((stripped, nums))
    return refs


def find_unreferenced_claims(text: str) -> list[str]:
    """Return body claims with no trailing `[n]` marker and no exemption
    (same Faction:/Current location:/Current goals:/bare-absence exemption
    as the extract pass's find_uncited_bullets)."""
    body, _ = _split_body_and_citations(text)
    unreferenced = []
    for line in body.splitlines():
        stripped = line.strip()
        if (stripped.startswith('- ')
                and not _TRAILING_ENDNOTE_REFS_RE.search(stripped)
                and not _is_exempt_from_citation(stripped)):
            unreferenced.append(stripped)
    return unreferenced


def find_dangling_refs(text: str) -> list[int]:
    """Endnote numbers referenced inline with no matching `## Citations` entry."""
    definitions = extract_endnote_definitions(text)
    referenced = {n for _, nums in find_endnote_refs(text) for n in nums}
    return sorted(referenced - definitions.keys())


def find_orphan_definitions(text: str) -> list[int]:
    """`## Citations` entries never referenced inline — a hygiene issue,
    not a hallucination risk (the quote is still real, just unused)."""
    definitions = extract_endnote_definitions(text)
    referenced = {n for _, nums in find_endnote_refs(text) for n in nums}
    return sorted(definitions.keys() - referenced)


def verify_endnotes(text: str, known_citations: set[str]) -> list[Endnote]:
    """Check every `## Citations` entry's quote is an exact (normalized)
    member of `known_citations` — the union of `[cite: "..."]` quotes
    already present in the extraction notes synthesis was given. Synthesis
    is required to copy a citation forward, not invent one, so this is
    set-membership rather than a fuzzy substring search.
    """
    known_normalized = {_normalize(q) for q in known_citations}
    definitions = extract_endnote_definitions(text)
    return [
        Endnote(number=n, quote=q, verified=bool(q) and _normalize(q) in known_normalized)
        for n, q in sorted(definitions.items())
    ]


def render_synthesis_report(endnotes: list[Endnote], unreferenced: list[str],
                             dangling: list[int], orphans: list[int]) -> str:
    """Render a synthesis_citation_report.md body.

    endnotes     — from verify_endnotes(); unverified entries are flagged.
    unreferenced — claims with no [n] marker, from find_unreferenced_claims().
    dangling     — [n] used inline with no matching `## Citations` entry.
    orphans      — `## Citations` entries never referenced inline (hygiene only).
    """
    unverified = [e for e in endnotes if not e.verified]
    lines = [
        "# Synthesis Citation Report",
        "",
        "Generated by distill.py's synthesis citation check (plain set-membership,"
        " not a model call). Every claim in the synthesized document is expected"
        " to carry an `[n]` endnote whose quote was copied verbatim from the"
        " extraction notes' own `[cite: \"...\"]` tags.",
    ]
    if not unverified and not unreferenced and not dangling and not orphans:
        lines += ["", "No flagged claims — every endnote traces to a citation"
                       " already present in the extraction notes."]
        return "\n".join(lines) + "\n"
    if unverified:
        lines += ["", "### Endnotes not found in any extraction file (candidate fabrication)"]
        for e in unverified:
            lines.append(f'- [{e.number}] "{e.quote}"')
    if unreferenced:
        lines += ["", "### Claims missing an endnote"]
        for claim in unreferenced:
            lines.append(f"- {claim}")
    if dangling:
        lines += ["", "### Endnote markers with no matching Citations entry"]
        for n in dangling:
            lines.append(f"- [{n}]")
    if orphans:
        lines += ["", "### Citations entries never referenced (hygiene only, not a hallucination risk)"]
        for n in orphans:
            lines.append(f"- [{n}]")
    return "\n".join(lines) + "\n"
